LatNet Builder Manual: NetBuilder::FigureOfMerit::CombinedFigureOfMerit Class Reference
NetBuilder::FigureOfMerit::CombinedFigureOfMerit Class Reference
Aggregation of figures of merit computed in a specific order.
#include <CombinedFigureOfMerit.h>
Inherits NetBuilder::FigureOfMerit::CBCFigureOfMerit.
Public Member Functions
CombinedFigureOfMerit (Real normType, std::vector< std::unique_ptr< CBCFigureOfMerit > > figures, std::vector< Real > weights)
Constructor.
Real normType () const
Returns the norm type of the figure.
virtual Accumulator accumulator (Real initialValue) const override
Creates a new accumulator.
std::vector< Real > weights () const
Returns the vector of weights.
unsigned int size () const
Returns the number of figures.
CBCFigureOfMerit * pointerToFigure (unsigned int num) const
Returns a pointer to the figure in position num.
virtual std::unique_ptr< CBCFigureOfMeritEvaluator > evaluator () override
Returns a std::unique_ptr to an evaluator for the figure of merit.
Real expNorm () const
Returns the exponent to use when accumulating merits.
virtual std::string format () const override
Output information about the figure of merit.
Public Member Functions inherited from NetBuilder::FigureOfMerit::CBCFigureOfMerit
virtual ~CBCFigureOfMerit ()=default
Virtual default destructor.
Public Member Functions inherited from NetBuilder::FigureOfMerit::FigureOfMerit
virtual ~FigureOfMerit ()=default
Virtual default destructor.
std::unique_ptr< FigureOfMeritEvaluator > evaluator ()
Returns a std::unique_ptr to an evaluator for the figure of merit.
Detailed Description
Aggregation of figures of merit computed in a specific order.
Constructor & Destructor Documentation
CombinedFigureOfMerit()
NetBuilder::FigureOfMerit::CombinedFigureOfMerit::CombinedFigureOfMerit (Real normType, std::vector< std::unique_ptr< CBCFigureOfMerit > > figures, std::vector< Real > weights) inline
Constructor.
Parameters
normType Norm type use in the aggregation of merits
figures Vector of figures of merit
weights Vector of weights
References normType(), size(), and weights().
Member Function Documentation
accumulator()
virtual Accumulator NetBuilder::FigureOfMerit::CombinedFigureOfMerit::accumulator (Real initialValue) const inline override virtual
Creates a new accumulator.
Parameters
initialValue Initial accumulator value.
Implements NetBuilder::FigureOfMerit::CBCFigureOfMerit.
evaluator()
virtual std::unique_ptr< CBCFigureOfMeritEvaluator > NetBuilder::FigureOfMerit::CombinedFigureOfMerit::evaluator () inline override virtual
Returns a std::unique_ptr to an evaluator for the figure of merit.
Implements NetBuilder::FigureOfMerit::CBCFigureOfMerit.
format()
virtual std::string NetBuilder::FigureOfMerit::CombinedFigureOfMerit::format () const inline override virtual
Output information about the figure of merit.
Implements NetBuilder::FigureOfMerit::FigureOfMerit.
The documentation for this class was generated from the following file:
include/netbuilder/FigureOfMerit/CombinedFigureOfMerit.h