LatNet Builder Manual: NetBuilder::FigureOfMerit::ResolutionGapProjMerit< EmbeddingType::MULTILEVEL > Class Template Reference
NetBuilder::FigureOfMerit::ResolutionGapProjMerit< EmbeddingType::MULTILEVEL > Class Template Reference
Template specialization of the projection-dependent merit defined by the resolution-gap of the projection in the case of multilevel nets.
#include <ResolutionGapProjMerit.h>
Public Types
typedef std::unique_ptr< LevelCombiner::LevelCombiner > pCombiner
Public Member Functions
ResolutionGapProjMerit (unsigned int maxCardinal, pCombiner combiner=std::make_unique< LevelCombiner::LevelCombiner >())
Constructs a projection-dependent merit based on the resolution-gap of projections.
unsigned int maxCardinal () const
Returns the maximum order of the subprojections to take into account.
std::string format () const
Output information about the figure of merit.
Real operator() (const DigitalNet &net, const LatticeTester::Coordinates &projection)
Computes the projection-dependent merit of the net net for the given projection.
CBCCoordinateSet projections (Dimension dimension) const
Returns the projections to include in the figure of merit partial computation for dimension dimension.
Real combine (const std::vector< unsigned int > &merits)
Combines the vector of multilevel merits into a single value merit.
Detailed Description
template<>
class NetBuilder::FigureOfMerit::ResolutionGapProjMerit< EmbeddingType::MULTILEVEL >
Template specialization of the projection-dependent merit defined by the resolution-gap of the projection in the case of multilevel nets.
See also
NetBuilder::ResolutionGapProjMerit
Constructor & Destructor Documentation
ResolutionGapProjMerit()
NetBuilder::FigureOfMerit::ResolutionGapProjMerit< EmbeddingType::MULTILEVEL >::ResolutionGapProjMerit (unsigned int maxCardinal, pCombiner combiner = std::make_unique<LevelCombiner::LevelCombiner>()) inline
Constructs a projection-dependent merit based on the resolution-gap of projections.
Parameters
maxCardinal Maximum order of the subprojections.
combiner LevelCombiner used to combine multilevel merits.
Member Function Documentation
combine()
Real NetBuilder::FigureOfMerit::ResolutionGapProjMerit< EmbeddingType::MULTILEVEL >::combine (const std::vector< unsigned int > & merits) inline
Combines the vector of multilevel merits into a single value merit.
Parameters
merits Multilevel merits to combine.
operator()()
Real NetBuilder::FigureOfMerit::ResolutionGapProjMerit< EmbeddingType::MULTILEVEL >::operator() (const DigitalNet & net, const LatticeTester::Coordinates & projection) inline
Computes the projection-dependent merit of the net net for the given projection.
Parameters
net Digital to evaluate.
projection Projection to use.
References NetBuilder::DigitalNet::generatingMatrix(), NetBuilder::DigitalNet::numColumns(), NetBuilder::DigitalNet::numRows(), and NetBuilder::GeneratingMatrix::subMatrix().
projections()
CBCCoordinateSet NetBuilder::FigureOfMerit::ResolutionGapProjMerit< EmbeddingType::MULTILEVEL >::projections (Dimension dimension) const inline
Returns the projections to include in the figure of merit partial computation for dimension dimension.
Parameters
dimension Dimension of the partial computation.
The documentation for this class was generated from the following file:
include/netbuilder/FigureOfMerit/ResolutionGapProjMerit.h