LatNet Builder Manual: LatBuilder::MeritSeq::CBC< LR, ET, COMPRESS, PLO, PROJDEP, ACC > Class Template Reference
LatBuilder::MeritSeq::CBC< LR, ET, COMPRESS, PLO, PROJDEP, ACC > Class Template Reference
Sequence of lattice merit for CBC exploration.
#include <CBC.h>
Classes
class Seq
Output sequence of merit values.
Public Types
typedef WeightedFigureOfMerit< PROJDEP, ACC > FigureOfMerit
typedef Storage< LR, ET, COMPRESS, PLO >::MeritValue MeritValue
typedef LatBuilder::LatDef< LR, ET > LatDef
typedef MeritValue value_type
typedef LatticeTester::CoordinateSets::AddCoordinate< LatticeTester::CoordinateSets::FromRanges > Projections
Public Member Functions
CBC (Storage< LR, ET, COMPRESS, PLO > storage, const FigureOfMerit &figure)
Constructor.
void reset ()
Resets the state of the CBC algorithm to dimension 0.
const Storage< LR, ET, COMPRESS, PLO > & storage () const
Returns the storage configuration instance.
const FigureOfMerit & figureOfMerit () const
Returns the figure of merit.
const Evaluator & evaluator () const
Returns the figure of merit evaluator.
const LatDef & baseLat () const
Returns the base lattice.
const MeritValue & baseMerit () const
Returns the base merit value.
Projections projections () const
Returns a sequence of coordinate sets corresponding to the all projections that comprise the next coordinate to be appended.
template<typename GENSEQ >
Seq< GENSEQ > meritSeq (GENSEQ genSeq) const
Creates a new sequence of merit values by appending the values in genSeq to the generating vector of the base lattice.
template<typename IT >
void select (const IT &it)
Selects the element pointed to by the iterator.
Public Attributes
decltype(std::declval< FigureOfMerit >().evaluator(std::declval< Storage< LR, ET, COMPRESS, PLO >>())) typedef Evaluator
Detailed Description
template<LatticeType LR, EmbeddingType ET, Compress COMPRESS, PerLevelOrder PLO, class PROJDEP, template< typename > class ACC>
class LatBuilder::MeritSeq::CBC< LR, ET, COMPRESS, PLO, PROJDEP, ACC >
Sequence of lattice merit for CBC exploration.
This class is intended to be used with the following steps:
Instantiate. At that point, the dimension is zero.
Iterate over the sequence of merit values and lattices for the next dimension with CBC::Seq::begin() and CBC::Seq::end().
Select an element from the sequence with select(). This increases the current dimension by one.
Repeat from step 2 until desired dimension is reached.
Constructor & Destructor Documentation
CBC()
template<LatticeType LR, EmbeddingType ET, Compress COMPRESS, PerLevelOrder PLO, class PROJDEP, template< typename > class ACC> LatBuilder::MeritSeq::CBC< LR, ET, COMPRESS, PLO, PROJDEP, ACC >::CBC (Storage< LR, ET, COMPRESS, PLO > storage, const FigureOfMerit & figure) inline
Constructor.
Parameters
storage Storage configuration.
figure Figure of merit instance to be used.
Member Function Documentation
baseLat()
template<LatticeType LR, EmbeddingType ET, Compress COMPRESS, PerLevelOrder PLO, class PROJDEP, template< typename > class ACC> const LatDef& LatBuilder::MeritSeq::CBC< LR, ET, COMPRESS, PLO, PROJDEP, ACC >::baseLat () const inline
Returns the base lattice.
This sequence extends on the lattice base by increasing its dimension by one.
See also
baseMerit()
Referenced by LatBuilder::MeritSeq::LatSeqOverCBC< CBC >::Seq< LATSEQ >::element(), LatBuilder::MeritSeq::CBC< LR, ET, COMPRESS, PLO, PROJDEP, ACC >::meritSeq(), and LatBuilder::MeritSeq::CBC< LR, ET, COMPRESS, PLO, PROJDEP, ACC >::projections().
baseMerit()
template<LatticeType LR, EmbeddingType ET, Compress COMPRESS, PerLevelOrder PLO, class PROJDEP, template< typename > class ACC> const MeritValue& LatBuilder::MeritSeq::CBC< LR, ET, COMPRESS, PLO, PROJDEP, ACC >::baseMerit () const inline
Returns the base merit value.
The merit values contained in this sequence are based on the value returned by this function.
See also
baseLat()
Referenced by LatBuilder::MeritSeq::LatSeqOverCBC< CBC >::Seq< LATSEQ >::element(), and LatBuilder::MeritSeq::CBC< LR, ET, COMPRESS, PLO, PROJDEP, ACC >::Seq< GENSEQ >::element().
meritSeq()
template<LatticeType LR, EmbeddingType ET, Compress COMPRESS, PerLevelOrder PLO, class PROJDEP, template< typename > class ACC> template<typename GENSEQ > Seq<GENSEQ> LatBuilder::MeritSeq::CBC< LR, ET, COMPRESS, PLO, PROJDEP, ACC >::meritSeq (GENSEQ genSeq) const inline
Creates a new sequence of merit values by appending the values in genSeq to the generating vector of the base lattice.
Parameters
genSeq Sequence of generator values.
References LatBuilder::MeritSeq::CBC< LR, ET, COMPRESS, PLO, PROJDEP, ACC >::baseLat(), and LatBuilder::LatSeq::cbc().
Referenced by LatBuilder::MeritSeq::LatSeqOverCBC< CBC >::Seq< LATSEQ >::element().
select()
template<LatticeType LR, EmbeddingType ET, Compress COMPRESS, PerLevelOrder PLO, class PROJDEP, template< typename > class ACC> template<typename IT > void LatBuilder::MeritSeq::CBC< LR, ET, COMPRESS, PLO, PROJDEP, ACC >::select (const IT & it) inline
Selects the element pointed to by the iterator.
Returns true if and only if the sequence of generator sequences is not exhausted.
Parameters
it Iterator on the element of the sequence to be selected.
Referenced by LatBuilder::MeritSeq::LatSeqOverCBC< CBC >::Seq< LATSEQ >::element().
The documentation for this class was generated from the following file:
include/latbuilder/MeritSeq/CBC.h