LatNet Builder Manual: LatticeTester::IntLattice< Int, BasInt, BasIntVec, BasIntMat, Dbl, DblVec, RedDbl > Class Template Reference
LatticeTester::IntLattice< Int, BasInt, BasIntVec, BasIntMat, Dbl, DblVec, RedDbl > Class Template Reference
This class is a skeleton for the implementation of different types of lattices of arbitrary rank.
#include <IntLattice.h>
Inherits LatticeTester::IntLatticeBasis< Int, BasInt, BasIntVec, BasIntMat, Dbl, DblVec, RedDbl >.
Inherited by LatticeTester::Rank1Lattice< Int, IntVec, BasInt, BasIntVec, BasIntMat, Dbl, DblVec, RedDbl >.
Public Member Functions
IntLattice (Int modulo, int k, int maxDim, NormType norm=L2NORM)
Constructor initializing the primal and the dual basis with the identity matrix.
IntLattice (const IntLattice< Int, BasInt, BasIntVec, BasIntMat, Dbl, DblVec, RedDbl > &Lat)
Copy constructor that makes a copy of Lat.
void copy (const IntLattice< Int, BasInt, BasIntVec, BasIntMat, Dbl, DblVec, RedDbl > &lattice)
Copies lattice into this object.
virtual ~IntLattice ()
Destructor.
void init ()
Allocates space to vectors used internally.
int getOrder () const
This is the order of the underlying MRG.
virtual void incDim ()
Increments the dimension of the basis and dual basis vectors by one.
void calcLgVolDual2 (double lgm2)
Computes the logarithm of the normalization factor (m_lgVolDual2) in all dimensions \(\leq\) MaxDim for the lattice.
double getLgVolDual2 (int i) const
Gives the log of m^(2*i) if i < order, else gives the log of m^(2*i)
void dualize ()
Exchange the primal basis and the dual basis.
void fixLatticeNormalization (bool dualF)
This function is called to fix the normalization constants to get the normalized merit from the shortest distance in the lattice.
void buildProjection (IntLattice< Int, BasInt, BasIntVec, BasIntMat, Dbl, DblVec, RedDbl > *lattice, const Coordinates &proj)
Builds the basis (and dual basis) of the projection proj for this lattice.
virtual void buildBasis (int d)
Builds the basis for the lattice in dimension d.
LatticeTester::Normalizer< RedDbl > * getNormalizer (NormaType norma, int alpha, bool dualF)
Creates and returns the normalizer corresponding to criterion norma.
virtual void setLac (const Lacunary< BasInt, BasIntVec > &)
Does nothing is this base class.
virtual std::string toStringCoef () const
Returns the vector of multipliers (or coefficients) \(A\) as a string.
Public Member Functions inherited from LatticeTester::IntLatticeBasis< Int, BasInt, BasIntVec, BasIntMat, Dbl, DblVec, RedDbl >
IntLatticeBasis (const int dim, NormType norm=L2NORM)
Constructor initializing the primal basis with the identity matrix.
IntLatticeBasis (const BasIntMat basis, const int dim, NormType norm=L2NORM)
Constructor taking all three needed component of an IntLatticeBasis.
IntLatticeBasis (const BasIntMat primalbasis, const BasIntMat dualbasis, const Int modulo, const int dim, NormType norm=L2NORM)
Complete constructor.
IntLatticeBasis (const IntLatticeBasis< Int, BasInt, BasIntVec, BasIntMat, Dbl, DblVec, RedDbl > &Lat)
Copy constructor.
~IntLatticeBasis ()
Destructor.
void kill ()
Cleans and releases all the memory allocated to this lattice.
void copyBasis (const IntLatticeBasis< Int, BasInt, BasIntVec, BasIntMat, Dbl, DblVec, RedDbl > &lat)
Copy the lattice lat, except it's NormType and dimension, into this object.
void copyBasis (const IntLatticeBasis< Int, BasInt, BasIntVec, BasIntMat, Dbl, DblVec, RedDbl > &lat, int n)
Copy the n first elements of the lattice lat into this object.
void initVecNorm ()
Initializes a vector containing the norms of the basis vectors to -1 at all components.
BasIntMat & getBasis ()
Returns the basis in a BasIntMat-type matrix.
BasIntMat & getDualBasis ()
Returns the dual basis in a BasIntMat-type Matrix.
int getDim () const
Returns the dimension of the lattice.
NormType getNorm () const
Returns the NormType used by this lattice.
Dbl getVecNorm (const int &i)
Returns the norm of the i-th vector of the basis.
DblVec getVecNorm () const
Returns the norm of each vector of the basis.
Dbl getDualVecNorm (const int &i)
Returns the norm of the i-th vector of the dual basis.
DblVec getDualVecNorm () const
Returns the norm of each vector of the dual basis.
Int getModulo () const
Returns the m used by the dual and for rescaling.
void setDim (const int &d)
Sets the dimension of the basis to d.
void setNorm (const NormType &norm)
Sets the NormType used by this lattice to norm.
void setVecNorm (const Dbl &value, const int &i)
Sets the norm of the i-th component of the basis to value.
void setDualVecNorm (const Dbl &value, const int &i)
Sets the norm of the i-th component of the dual basis to value.
bool withDual ()
Returns true if a dual has been defined and false otherwise.
void setDualFlag (bool flag)
Sets the withDual flag to flag.
bool getXX (int i) const
Gets whether or not there is a component at the i-th position in the basis.
void setXX (bool val, int i)
Sets value at the i-th position in the array xx.
void setNegativeNorm ()
Sets all the values in the array containing the norms of the basis vectors to -1.
void setNegativeNorm (const int &i)
Sets the value of the i-th component in the array containing the norms of the basis vectors to -1.
void setDualNegativeNorm ()
Sets all the values in the array containing the norms of the dual basis vectors to -1.
void setDualNegativeNorm (const int &i)
Sets the value of the i-th component in the array containing the norms of the dual basis vectors to -1.
void updateVecNorm ()
Updates the array containing the basis vectors norms by recomputing them.
void updateVecNorm (const int &d)
Updates the array containing the basis vectors norms from the d-th component to the last by recomputing them.
void updateDualVecNorm ()
Updates the array containing the dual basis vectors norms by recomputing them.
void updateDualVecNorm (const int &d)
Updates the array containing the dual basis vectors norms from the d-th component to the last by recomputing them.
void updateScalL2Norm (const int i)
Updates the i-th value of the array containing the norms of the basis vectors by recomputing it using the L2NORM.
void updateScalL2Norm (const int k1, const int k2)
Updates the k1-th to the k2-1-th values of the array containing the norms of the basis vectors by recomputing them using the L2NORM.
void updateDualScalL2Norm (const int i)
Updates the i-th value of the array containing the norms of the dual basis vectors by recomputing it using the L2NORM.
void updateDualScalL2Norm (const int k1, const int k2)
Updates the k1-th to the k2-1-th values of the array containing the norms of the dual basis vectors by recomputing them using the L2NORM.
void permute (int i, int j)
Exchanges vectors i and j in the basis.
bool checkDuality ()
Returns true if the dual basis contained in the object really is the dual of the basis, and false otherwise.
void sort (int d)
Sorts the basis vectors with indices greater of equal to \(d\) by increasing length.
std::string toStringBasis () const
Returns a string with the primal basis and its norms.
std::string toStringDualBasis () const
Returns a string with the dual basis and its norms.
void write () const
Writes the lattice and its parameters on standard output.
Protected Member Functions
virtual void kill ()
The components of the lattice when it is built out of more than one component.
Protected Attributes
int m_order
The order of the basis.
double * m_lgVolDual2
Represente sur dual along the diagonal?? ERWAN.
double m_lgm2
The logarithm \(\log_2 (m^2)\).
BasIntMat m_wSI
Use to save the dual basis and the basis in some works.
BasIntMat m_vSI
Int m_t1
Working Variables use in MRGLattice.h.
Int m_t2
Int m_t3
Protected Attributes inherited from LatticeTester::IntLatticeBasis< Int, BasInt, BasIntVec, BasIntMat, Dbl, DblVec, RedDbl >
BasIntMat m_basis
Each row of this matrix represents a vector in the basis of the lattice.
BasIntMat m_dualbasis
Each row of this matrix represents a vector in the dual basis of the lattice.
int m_dim
The dimension of the lattice.
NormType m_norm
The NormType used in the reduction and for this lattice.
DblVec m_vecNorm
The norm of each vector in the basis.
DblVec m_dualvecNorm
The norm of each vector in the dual basis.
Int m_modulo
The m associated to the m-dual.
bool m_withDual
If m_withDual is true a dual basis has been specified, otherwise it is false.
bool * m_xx
This table is used in the Minkowski reduction.
Detailed Description
template<typename Int, typename BasInt, typename BasIntVec, typename BasIntMat, typename Dbl, typename DblVec, typename RedDbl>
class LatticeTester::IntLattice< Int, BasInt, BasIntVec, BasIntMat, Dbl, DblVec, RedDbl >
This class is a skeleton for the implementation of different types of lattices of arbitrary rank.
This class contains a method to compute lattices of projections of \(\{x_i\}_{ 0 \leq i}\), a method to exchange the basis and the dual basis, and a virtual method that can be implemented in subclasses to recompute the basis for different dimensions.
A lattice of rank \(k\) with integer vectors modulo \(m\) contains \(m^k\) distinct vectors. This number, the density, can then be used to compute bounds on the spectral test. This class implements methods to compute \(\log_2(m^{2i}) \) for \(1 \leq i \leq k \) to help with the computation of such bounds.
Constructor & Destructor Documentation
IntLattice() [1/2]
template<typename Int , typename BasInt , typename BasIntVec , typename BasIntMat , typename Dbl , typename DblVec , typename RedDbl > LatticeTester::IntLattice< Int, BasInt, BasIntVec, BasIntMat, Dbl, DblVec, RedDbl >::IntLattice (Int modulo, int k, int maxDim, NormType norm = L2NORM)
Constructor initializing the primal and the dual basis with the identity matrix.
The dimension of the lattice is set to maxDim and the norm used for reduction to norm.
Parameters
modulo The modulo of the integer coordinates
k The rank of the lattice to be constructed
maxDim The maximal dimension for which this lattice can be expanded/tested (?)
norm The norm to use in for reduction
References LatticeTester::IntLattice< Int, BasInt, BasIntVec, BasIntMat, Dbl, DblVec, RedDbl >::init(), LatticeTester::IntLatticeBasis< Int, BasInt, BasIntVec, BasIntMat, Dbl, DblVec, RedDbl >::m_dim, LatticeTester::IntLatticeBasis< Int, BasInt, BasIntVec, BasIntMat, Dbl, DblVec, RedDbl >::m_dualbasis, LatticeTester::IntLatticeBasis< Int, BasInt, BasIntVec, BasIntMat, Dbl, DblVec, RedDbl >::m_dualvecNorm, LatticeTester::IntLatticeBasis< Int, BasInt, BasIntVec, BasIntMat, Dbl, DblVec, RedDbl >::m_modulo, LatticeTester::IntLattice< Int, BasInt, BasIntVec, BasIntMat, Dbl, DblVec, RedDbl >::m_order, LatticeTester::IntLatticeBasis< Int, BasInt, BasIntVec, BasIntMat, Dbl, DblVec, RedDbl >::m_withDual, and LatticeTester::IntLatticeBasis< Int, BasInt, BasIntVec, BasIntMat, Dbl, DblVec, RedDbl >::setDualNegativeNorm().
IntLattice() [2/2]
template<typename Int , typename BasInt , typename BasIntVec , typename BasIntMat , typename Dbl , typename DblVec , typename RedDbl > LatticeTester::IntLattice< Int, BasInt, BasIntVec, BasIntMat, Dbl, DblVec, RedDbl >::IntLattice (const IntLattice< Int, BasInt, BasIntVec, BasIntMat, Dbl, DblVec, RedDbl > & Lat)
Copy constructor that makes a copy of Lat.
The maximal dimension of the created basis is set equal to Lats current dimension.
References LatticeTester::IntLattice< Int, BasInt, BasIntVec, BasIntMat, Dbl, DblVec, RedDbl >::init(), LatticeTester::IntLattice< Int, BasInt, BasIntVec, BasIntMat, Dbl, DblVec, RedDbl >::m_order, LatticeTester::IntLatticeBasis< Int, BasInt, BasIntVec, BasIntMat, Dbl, DblVec, RedDbl >::m_withDual, LatticeTester::IntLattice< Int, BasInt, BasIntVec, BasIntMat, Dbl, DblVec, RedDbl >::m_wSI, and LatticeTester::IntLatticeBasis< Int, BasInt, BasIntVec, BasIntMat, Dbl, DblVec, RedDbl >::setDualNegativeNorm().
Member Function Documentation
buildBasis()
template<typename Int , typename BasInt , typename BasIntVec , typename BasIntMat , typename Dbl , typename DblVec , typename RedDbl > void LatticeTester::IntLattice< Int, BasInt, BasIntVec, BasIntMat, Dbl, DblVec, RedDbl >::buildBasis (int d) virtual
Builds the basis for the lattice in dimension d.
This fonction is implemented in subclasses
Reimplemented in LatticeTester::Rank1Lattice< Int, IntVec, BasInt, BasIntVec, BasIntMat, Dbl, DblVec, RedDbl >.
References LatticeTester::MyExit().
buildProjection()
template<typename Int , typename BasInt , typename BasIntVec , typename BasIntMat , typename Dbl , typename DblVec , typename RedDbl > void LatticeTester::IntLattice< Int, BasInt, BasIntVec, BasIntMat, Dbl, DblVec, RedDbl >::buildProjection (IntLattice< Int, BasInt, BasIntVec, BasIntMat, Dbl, DblVec, RedDbl > * lattice, const Coordinates & proj)
Builds the basis (and dual basis) of the projection proj for this lattice.
The result is placed in the lattice lattice. The basis is triangularized to form a proper basis.
calcLgVolDual2()
template<typename Int , typename BasInt , typename BasIntVec , typename BasIntMat , typename Dbl , typename DblVec , typename RedDbl > void LatticeTester::IntLattice< Int, BasInt, BasIntVec, BasIntMat, Dbl, DblVec, RedDbl >::calcLgVolDual2 (double lgm2)
Computes the logarithm of the normalization factor (m_lgVolDual2) in all dimensions \(\leq\) MaxDim for the lattice.
lgm2 is the logarithm in base 2 of \(m^2\).
copy()
template<typename Int , typename BasInt , typename BasIntVec , typename BasIntMat , typename Dbl , typename DblVec , typename RedDbl > void LatticeTester::IntLattice< Int, BasInt, BasIntVec, BasIntMat, Dbl, DblVec, RedDbl >::copy (const IntLattice< Int, BasInt, BasIntVec, BasIntMat, Dbl, DblVec, RedDbl > & lattice)
Copies lattice into this object.
This should be equivalent to the creation of a new IntLattice using the copy constructor with lattice as an argument.
References LatticeTester::IntLattice< Int, BasInt, BasIntVec, BasIntMat, Dbl, DblVec, RedDbl >::getOrder().
fixLatticeNormalization()
template<typename Int , typename BasInt , typename BasIntVec , typename BasIntMat , typename Dbl , typename DblVec , typename RedDbl > void LatticeTester::IntLattice< Int, BasInt, BasIntVec, BasIntMat, Dbl, DblVec, RedDbl >::fixLatticeNormalization (bool dualF)
This function is called to fix the normalization constants to get the normalized merit from the shortest distance in the lattice.
If dualF is true, the normalization constant is reset for the dual lattice, otherwise it is reset for the primal lattice.
getNormalizer()
template<typename Int , typename BasInt , typename BasIntVec , typename BasIntMat , typename Dbl , typename DblVec , typename RedDbl > Normalizer< RedDbl > * LatticeTester::IntLattice< Int, BasInt, BasIntVec, BasIntMat, Dbl, DblVec, RedDbl >::getNormalizer (NormaType norma, int alpha, bool dualF)
Creates and returns the normalizer corresponding to criterion norma.
In the case of the \(P_{\alpha}\) test, the argument alpha = \(\alpha\). In all other cases, it is unused.
getOrder()
template<typename Int, typename BasInt, typename BasIntVec, typename BasIntMat, typename Dbl, typename DblVec, typename RedDbl> int LatticeTester::IntLattice< Int, BasInt, BasIntVec, BasIntMat, Dbl, DblVec, RedDbl >::getOrder () const inline
This is the order of the underlying MRG.
The problem is that the lattice is not necessarily associated with a MRG anymore. The solution probably is to change this so that it is now the rank because a MRG of order k spans a lattice of rank k. (See the lattice construction in Pierre's book)
References LatticeTester::IntLattice< Int, BasInt, BasIntVec, BasIntMat, Dbl, DblVec, RedDbl >::m_order.
Referenced by LatticeTester::IntLattice< Int, BasInt, BasIntVec, BasIntMat, Dbl, DblVec, RedDbl >::copy().
incDim()
template<typename Int , typename BasInt , typename BasIntVec , typename BasIntMat , typename Dbl , typename DblVec , typename RedDbl > void LatticeTester::IntLattice< Int, BasInt, BasIntVec, BasIntMat, Dbl, DblVec, RedDbl >::incDim () virtual
Increments the dimension of the basis and dual basis vectors by one.
This initializes the added components to 0 and does not compute the value taken by the added components and vector. It also resets vectors containing the norms. The implementation in this class is meant to be overriden by subclasses and probably should not be used.
Reimplemented in LatticeTester::Rank1Lattice< Int, IntVec, BasInt, BasIntVec, BasIntMat, Dbl, DblVec, RedDbl >.
References LatticeTester::IntLatticeBasis< Int, BasInt, BasIntVec, BasIntMat, Dbl, DblVec, RedDbl >::m_basis, LatticeTester::IntLatticeBasis< Int, BasInt, BasIntVec, BasIntMat, Dbl, DblVec, RedDbl >::m_dualbasis, LatticeTester::IntLatticeBasis< Int, BasInt, BasIntVec, BasIntMat, Dbl, DblVec, RedDbl >::m_dualvecNorm, and LatticeTester::IntLatticeBasis< Int, BasInt, BasIntVec, BasIntMat, Dbl, DblVec, RedDbl >::m_vecNorm.
init()
template<typename Int , typename BasInt , typename BasIntVec , typename BasIntMat , typename Dbl , typename DblVec , typename RedDbl > void LatticeTester::IntLattice< Int, BasInt, BasIntVec, BasIntMat, Dbl, DblVec, RedDbl >::init ()
Allocates space to vectors used internally.
This should probably be private or protected because it should not be needed to call it directly (the constructors and copy already call it.
References NTL::conv(), and LatticeTester::Lg().
Referenced by LatticeTester::Rank1Lattice< Int, IntVec, BasInt, BasIntVec, BasIntMat, Dbl, DblVec, RedDbl >::init(), and LatticeTester::IntLattice< Int, BasInt, BasIntVec, BasIntMat, Dbl, DblVec, RedDbl >::IntLattice().
kill()
template<typename Int , typename BasInt , typename BasIntVec , typename BasIntMat , typename Dbl , typename DblVec , typename RedDbl > void LatticeTester::IntLattice< Int, BasInt, BasIntVec, BasIntMat, Dbl, DblVec, RedDbl >::kill () protected virtual
The components of the lattice when it is built out of more than one component.
When there is only one component, it is unused as the parameters are the same as above. Cleans and releases all the memory allocated to this lattice.
The documentation for this class was generated from the following file:
latticetester/include/latticetester/IntLattice.h