LatNet Builder Manual: LatBuilder::Parser::Search< LR, ET > Class Template Reference
LatBuilder::Parser::Search< LR, ET > Class Template Reference
Parser for coordinate-uniform figures of merit.
#include <Search.h>
Static Public Member Functions
template<class FIGURE >
static std::unique_ptr< LatBuilder::Task::Search< LR, ET > > parse (const std::string &construction, LatBuilder::SizeParam< LR, ET > size, LatBuilder::Dimension dimension, FIGURE figure)
Parses a string specifying a construction method.
template<class FIGURE , class FUNC , typename... ARGS>
static void parse (const std::string &str, LatBuilder::SizeParam< LR, ET > size, LatBuilder::Dimension dimension, FIGURE figure, FUNC &&func, ARGS &&... args)
Parses a string specifying a construction method.
Detailed Description
template<LatticeType LR, LatBuilder::EmbeddingType ET>
class LatBuilder::Parser::Search< LR, ET >
Parser for coordinate-uniform figures of merit.
Member Function Documentation
parse() [1/2]
template<LatticeType LR, LatBuilder::EmbeddingType ET> template<class FIGURE > static std::unique_ptr< LatBuilder::Task::Search< LR, ET > > LatBuilder::Parser::Search< LR, ET >::parse (const std::string & construction, LatBuilder::SizeParam< LR, ET > size, LatBuilder::Dimension dimension, FIGURE figure) inline static
Parses a string specifying a construction method.
Example strings: full-CBC, fast-CBC, random-CBC:30
Returns
A pointer to a Search instance.
References LatBuilder::Parser::Search< LR, ET >::parse().
Referenced by LatBuilder::Parser::Search< LR, ET >::parse().
parse() [2/2]
template<LatticeType LR, LatBuilder::EmbeddingType ET> template<class FIGURE , class FUNC , typename... ARGS> static void LatBuilder::Parser::Search< LR, ET >::parse (const std::string & str, LatBuilder::SizeParam< LR, ET > size, LatBuilder::Dimension dimension, FIGURE figure, FUNC && func, ARGS &&... args) inline static
Parses a string specifying a construction method.
Calls func with the newly created search instance as its first argument, and args as additional arguments.
References LatBuilder::Task::cbc(), LatBuilder::createLatDef(), LatBuilder::Task::eval(), LatBuilder::Task::exhaustive(), LatBuilder::Task::extend(), LatBuilder::Task::fastCBC(), LatBuilder::Task::korobov(), LatBuilder::Task::random(), LatBuilder::Task::randomCBC(), and LatBuilder::Task::randomKorobov().
The documentation for this class was generated from the following file:
include/latbuilder/Parser/Search.h