LatNet Builder Manual: NetBuilder::Task::CBCSearch< NC, ET, EXPLORER, OBSERVER > Class Template Reference
NetBuilder::Task::CBCSearch< NC, ET, EXPLORER, OBSERVER > Class Template Reference
Class for CBC Search tasks.
#include <CBCSearch.h>
Inherits NetBuilder::Task::Search< NC, ET, MinimumObserver >.
Public Types
typedef EXPLORER< NC, ET > Explorer
Public Types inherited from NetBuilder::Task::Search< NC, ET, MinimumObserver >
typedef MinimumObserver< NC > Observer
Observer of the search.
typedef boost::signals2::signal< void(const Search< NC, ET, MinimumObserver > &)> OnNetSelected
Signal emitted when a net has been selected.
typedef boost::signals2::signal< void(const Search< NC, ET, MinimumObserver > &)> OnFailedSearch
Signal emitted when the search has failed.
Public Member Functions
CBCSearch (Dimension dimension, typename NetConstructionTraits< NC >::SizeParameter sizeParameter, std::unique_ptr< FigureOfMerit::CBCFigureOfMerit > figure, std::unique_ptr< Explorer > explorer=std::make_unique< Explorer >(), int verbose=0, bool earlyAbortion=false)
Constructor.
CBCSearch (Dimension dimension, std::unique_ptr< DigitalNet< NC > > baseNet, std::unique_ptr< FigureOfMerit::CBCFigureOfMerit > figure, std::unique_ptr< Explorer > explorer=std::make_unique< Explorer >(), int verbose=0, bool earlyAbortion=false)
Constructor.
CBCSearch (CBCSearch &&)=default
Default move constructor.
~CBCSearch ()=default
Default destructor.
virtual std::string format () const override
Returns information about the task.
virtual void execute () override
Executes the search task.
virtual void reset () override
Resets the search.
virtual const FigureOfMerit::CBCFigureOfMerit & figureOfMerit () const override
Returns a const qualified reference to the figure of merit.
Public Member Functions inherited from NetBuilder::Task::Search< NC, ET, MinimumObserver >
virtual ~Search ()=default
Virtual default destructor.
Search (Dimension dimension, typename NetConstructionTraits< NC >::SizeParameter sizeParameter, int verbose=0, bool earlyAbortion=false)
Constructor.
Dimension dimension () const
Returns the dimension of the searched net.
unsigned int nRows () const
Returns the number of rows of the searched generating matrices.
unsigned int nCols () const
Returns the number of columns of the searched generating matrices.
const DigitalNet< NC > & bestNet () const
Returns the best net found by the search.
Real bestMeritValue () const
Returns the best merit found by the search.
bool hasFoundNet () const
virtual std::string outputNet (OutputStyle outputStyle, unsigned int interlacingFactor) const override
Returns the best net found by the search task.
virtual Real outputMeritValue () const override
Returns the best merit value found by the search task.
Observer & observer ()
Returns a reference to the minimum-element observer.
OnNetSelected & onNetSelected ()
Net-selected signal.
OnFailedSearch & onFailedSearch ()
Failed search signal.
const NetConstructionTraits< NC >::SizeParameter & sizeParameter () const
Returns a const qualified reference to the size parameter of the search.
Additional Inherited Members
Protected Member Functions inherited from NetBuilder::Task::Search< NC, ET, MinimumObserver >
void selectBestNet (const DigitalNet< NC > &net, Real merit)
Selects a new best net and emits an OnNetSelected signal.
Protected Attributes inherited from NetBuilder::Task::Search< NC, ET, MinimumObserver >
std::unique_ptr< OnNetSelected > m_onNetSelected
std::unique_ptr< OnFailedSearch > m_onFailedSearch
Dimension m_dimension
NetConstructionTraits< NC >::SizeParameter m_sizeParameter
unsigned int m_nRows
unsigned int m_nCols
DigitalNet< NC > m_bestNet
Real m_bestMerit
std::unique_ptr< Observer > m_observer
int m_verbose
bool m_earlyAbortion
Detailed Description
template<NetConstruction NC, EmbeddingType ET, template< NetConstruction, EmbeddingType > class EXPLORER, template< NetConstruction > class OBSERVER = MinimumObserver>
class NetBuilder::Task::CBCSearch< NC, ET, EXPLORER, OBSERVER >
Class for CBC Search tasks.
Template template parameter EXPLORER must implement the following member functions:
void setVerbose() : set the verbosity level of the explorer.
void reset() : reset to its initial state the explorer.
void switchToCoordinate(Dimension coord) : switch the explorer to coordinate coord.
typename NetConstructionTraits<NC>::GenValue nextGenValue() : return the next generating value.
bool isOver() : indicate whether the exploration of the current coordinate is over. where NC is the template parameter of EXPLORER.
Constructor & Destructor Documentation
CBCSearch() [1/3]
template<NetConstruction NC, EmbeddingType ET, template< NetConstruction, EmbeddingType > class EXPLORER, template< NetConstruction > class OBSERVER = MinimumObserver> NetBuilder::Task::CBCSearch< NC, ET, EXPLORER, OBSERVER >::CBCSearch (Dimension dimension, typename NetConstructionTraits< NC >::SizeParameter sizeParameter, std::unique_ptr< FigureOfMerit::CBCFigureOfMerit > figure, std::unique_ptr< Explorer > explorer = std::make_unique<Explorer>(), int verbose = 0, bool earlyAbortion = false) inline
Constructor.
Parameters
dimension Dimension of the searched net.
sizeParameter Size parameter of the searched net.
figure Figure of merit used to compare nets.
explorer Explorer to search for nets.
verbose Verbosity level.
earlyAbortion Early-abortion switch. If true, the computations will be stopped if the net is worse than the best one so far.
References NetBuilder::Task::Search< NC, ET, MinimumObserver >::dimension(), NetBuilder::Task::Search< NC, ET, MinimumObserver >::Search(), and NetBuilder::Task::Search< NC, ET, MinimumObserver >::sizeParameter().
Referenced by CBCSearch().
CBCSearch() [2/3]
template<NetConstruction NC, EmbeddingType ET, template< NetConstruction, EmbeddingType > class EXPLORER, template< NetConstruction > class OBSERVER = MinimumObserver> NetBuilder::Task::CBCSearch< NC, ET, EXPLORER, OBSERVER >::CBCSearch (Dimension dimension, std::unique_ptr< DigitalNet< NC > > baseNet, std::unique_ptr< FigureOfMerit::CBCFigureOfMerit > figure, std::unique_ptr< Explorer > explorer = std::make_unique<Explorer>(), int verbose = 0, bool earlyAbortion = false) inline
Constructor.
Parameters
dimension Dimension of the searched net.
baseNet Net from which to start the search.
figure Figure of merit used to compare nets.
explorer Explorer to search for nets.
verbose Verbosity level.
earlyAbortion Early-abortion switch. If true, the computations will be stopped if the net is worse than the best one so far.
References NetBuilder::Task::Search< NC, ET, MinimumObserver >::dimension(), and NetBuilder::Task::Search< NC, ET, MinimumObserver >::Search().
CBCSearch() [3/3]
template<NetConstruction NC, EmbeddingType ET, template< NetConstruction, EmbeddingType > class EXPLORER, template< NetConstruction > class OBSERVER = MinimumObserver> NetBuilder::Task::CBCSearch< NC, ET, EXPLORER, OBSERVER >::CBCSearch (CBCSearch< NC, ET, EXPLORER, OBSERVER > &&) default
Default move constructor.
Deletes the implicit copy constructor.
References CBCSearch().
Member Function Documentation
execute()
template<NetConstruction NC, EmbeddingType ET, template< NetConstruction, EmbeddingType > class EXPLORER, template< NetConstruction > class OBSERVER = MinimumObserver> virtual void NetBuilder::Task::CBCSearch< NC, ET, EXPLORER, OBSERVER >::execute () inline override virtual
Executes the search task.
The best net and merit value are set in the process.
Implements NetBuilder::Task::Search< NC, ET, MinimumObserver >.
References NetBuilder::Task::MinimumObserver< NC >::bestNet(), NetBuilder::Task::Search< NC, ET, MinimumObserver >::bestNet(), NetBuilder::Task::Search< NC, ET, MinimumObserver >::dimension(), NetBuilder::Task::Search< NC, ET, MinimumObserver >::observer(), NetBuilder::Task::Search< NC, ET, MinimumObserver >::onFailedSearch(), NetBuilder::Task::Search< NC, ET, MinimumObserver >::Search(), and NetBuilder::Task::Search< NC, ET, MinimumObserver >::selectBestNet().
figureOfMerit()
template<NetConstruction NC, EmbeddingType ET, template< NetConstruction, EmbeddingType > class EXPLORER, template< NetConstruction > class OBSERVER = MinimumObserver> virtual const FigureOfMerit::CBCFigureOfMerit & NetBuilder::Task::CBCSearch< NC, ET, EXPLORER, OBSERVER >::figureOfMerit () const inline override virtual
Returns a const qualified reference to the figure of merit.
Implements NetBuilder::Task::Search< NC, ET, MinimumObserver >.
format()
template<NetConstruction NC, EmbeddingType ET, template< NetConstruction, EmbeddingType > class EXPLORER, template< NetConstruction > class OBSERVER = MinimumObserver> virtual std::string NetBuilder::Task::CBCSearch< NC, ET, EXPLORER, OBSERVER >::format () const inline override virtual
Returns information about the task.
Reimplemented from NetBuilder::Task::Search< NC, ET, MinimumObserver >.
reset()
template<NetConstruction NC, EmbeddingType ET, template< NetConstruction, EmbeddingType > class EXPLORER, template< NetConstruction > class OBSERVER = MinimumObserver> virtual void NetBuilder::Task::CBCSearch< NC, ET, EXPLORER, OBSERVER >::reset () inline override virtual
Resets the search.
Reimplemented from NetBuilder::Task::Search< NC, ET, MinimumObserver >.
References NetBuilder::Task::Search< NC, ET, OBSERVER >::reset().
The documentation for this class was generated from the following file:
include/netbuilder/Task/CBCSearch.h