LatNet Builder Manual: LatBuilder::Functor::MinElement< T > Struct Template Reference
LatBuilder::Functor::MinElement< T > Struct Template Reference
Minimum element functor.
#include <MinElement.h>
Public Types
typedef boost::signals2::signal< void(const size_t &)> OnStart
typedef boost::signals2::signal< void()> OnStop
typedef boost::signals2::signal< void(const T &)> OnMinUpdated
typedef boost::signals2::signal< bool(const T &), Functor::AllOf > OnElementVisited
Public Member Functions
MinElement ()
Constructor.
template<typename ForwardIterator >
ForwardIterator operator() (ForwardIterator first, ForwardIterator last, size_t maxAcceptedCount, int verbose=0) const
Returns an iterator pointing to the minimum element between first and last (exclusively).
OnStart & onStart ()
Start signal.
const OnStart & onStart () const
OnStop & onStop ()
Stop signal.
const OnStop & onStop () const
const OnMinUpdated & onMinUpdated () const
Minimum-updated signal.
OnMinUpdated & onMinUpdated ()
OnElementVisited & onElementVisited ()
Element-visited updated signal.
const OnElementVisited & onElementVisited () const
Detailed Description
template<typename T>
struct LatBuilder::Functor::MinElement< T >
Minimum element functor.
Re-implementation of std::min_element that emits a MinElement::onMinUpdated() signal when the current minimum value is updated.
Examples
tutorial/FilteredRCBC.cc, and tutorial/MeritSeqCBCSignals.cc.
Member Function Documentation
onElementVisited()
template<typename T > OnElementVisited & LatBuilder::Functor::MinElement< T >::onElementVisited () inline
Element-visited updated signal.
Emitted after an element is visited.
Examples
tutorial/FilteredRCBC.cc.
Referenced by LatBuilder::Functor::MinElement< T >::operator()().
onMinUpdated()
template<typename T > const OnMinUpdated & LatBuilder::Functor::MinElement< T >::onMinUpdated () const inline
Minimum-updated signal.
Emitted when the current minimum value has been updated.
Examples
tutorial/MeritSeqCBCSignals.cc.
Referenced by LatBuilder::Functor::MinElement< T >::operator()().
onStart()
template<typename T > OnStart & LatBuilder::Functor::MinElement< T >::onStart () inline
Start signal.
Emitted before the search begins.
Examples
tutorial/FilteredRCBC.cc.
Referenced by LatBuilder::Functor::MinElement< T >::operator()().
onStop()
template<typename T > OnStop & LatBuilder::Functor::MinElement< T >::onStop () inline
Stop signal.
Emitted after the search ends.
Referenced by LatBuilder::Functor::MinElement< T >::operator()().
operator()()
template<typename T > template<typename ForwardIterator > ForwardIterator LatBuilder::Functor::MinElement< T >::operator() (ForwardIterator first, ForwardIterator last, size_t maxAcceptedCount, int verbose = 0) const inline
Returns an iterator pointing to the minimum element between first and last (exclusively).
A start and a stop signals are emitted before the search begins and after it ends, respectively. A minimum-updated signal is emitted when the minimum is updated. An element-visited signal is emitted after an element has been visited.
References LatBuilder::Functor::MinElement< T >::onElementVisited(), LatBuilder::Functor::MinElement< T >::onMinUpdated(), LatBuilder::Functor::MinElement< T >::onStart(), and LatBuilder::Functor::MinElement< T >::onStop().
The documentation for this struct was generated from the following file:
include/latbuilder/Functor/MinElement.h