LatNet Builder Manual: LatticeTester::CoordinateSets::AddCoordinate< BASE >::const_iterator Class Reference
LatticeTester::CoordinateSets::AddCoordinate< BASE >::const_iterator Class Reference
An iterator class used internaly by the AddCoordinate class.
#include <CoordinateSets.h>
Inherits std::iterator< std::forward_iterator_tag, const Coordinates >.
Classes
struct end_tag
Public Member Functions
const_iterator (const AddCoordinate &seq)
Constructor for an iterator at the beginning of the list of sets that seq contains.
const_iterator (const AddCoordinate &seq, end_tag)
Constructor for an iterator at the end of the list of sets that seq contains.
const_iterator (const const_iterator &other)
Copy constructor.
const_iterator ()
Default constructor.
const_iterator & operator= (const const_iterator &other)
Assignment operator.
bool operator== (const const_iterator &other)
Compares this instance with other, returning true if they are associated with the same AddCoordinate object and if they are at the same point in their enumeration cycle.
bool operator!= (const const_iterator &other)
Compares this instance with other, returning false if they are associated with the same AddCoordinate object and if they are at the same point in their enumeration cycle.
const_iterator & operator++ ()
Prefix increment operator.
const_iterator operator++ (int)
Postfix increment operator.
const Coordinates & operator* () const
Dereference operator that returns the Coordinates this iterator is at.
Detailed Description
template<typename BASE>
class LatticeTester::CoordinateSets::AddCoordinate< BASE >::const_iterator
An iterator class used internaly by the AddCoordinate class.
Given an object of this class, it is possible to cycle through the element it contains with the increment (++) operator.
Since this iterator is built upon another object, it internally keeps an iterator that cycles through the sets generated by the CoordinateSets implementation the associated to the AddCoordinate object used for construction.
Constructor & Destructor Documentation
const_iterator()
template<typename BASE> LatticeTester::CoordinateSets::AddCoordinate< BASE >::const_iterator::const_iterator () inline
Default constructor.
Does nothing.
Member Function Documentation
operator++() [1/2]
template<typename BASE> const_iterator & LatticeTester::CoordinateSets::AddCoordinate< BASE >::const_iterator::operator++ () inline
Prefix increment operator.
This increments the underlying subset and updates m_value.
References const_iterator().
operator++() [2/2]
template<typename BASE> const_iterator LatticeTester::CoordinateSets::AddCoordinate< BASE >::const_iterator::operator++ (int) inline
Postfix increment operator.
This increments the underlying subset and updates m_value.
References const_iterator().
operator=()
template<typename BASE> const_iterator & LatticeTester::CoordinateSets::AddCoordinate< BASE >::const_iterator::operator= (const const_iterator & other) inline
Assignment operator.
This copies the left hand side object in the right hand side object.
References const_iterator().
The documentation for this class was generated from the following file:
latticetester/include/latticetester/CoordinateSets.h