var examples =
[
    [ "quantiles.cc", "d7/dfb/quantiles_8cc-example.html", null ],
    [ "tutorial/FilteredCBC.cc", "d9/dd1/tutorial_2FilteredCBC_8cc-example.html", null ],
    [ "tutorial/FilteredRCBC.cc", "d8/d0a/tutorial_2FilteredRCBC_8cc-example.html", null ],
    [ "tutorial/GenSeqCyclicGroup.cc", "d3/dc5/tutorial_2GenSeqCyclicGroup_8cc-example.html", null ],
    [ "tutorial/GenSeqExtend.cc", "de/dac/tutorial_2GenSeqExtend_8cc-example.html", null ],
    [ "tutorial/GenSeqGeneratingValues.cc", "da/d14/tutorial_2GenSeqGeneratingValues_8cc-example.html", null ],
    [ "tutorial/GenSeqRandom.cc", "d5/d9b/tutorial_2GenSeqRandom_8cc-example.html", null ],
    [ "tutorial/GenSeqVector.cc", "d2/d49/tutorial_2GenSeqVector_8cc-example.html", null ],
    [ "tutorial/LatDef.cc", "d3/db2/tutorial_2LatDef_8cc-example.html", null ],
    [ "tutorial/LatSeqCBC.cc", "d0/d84/tutorial_2LatSeqCBC_8cc-example.html", null ],
    [ "tutorial/LatSeqCBC1.cc", "d8/d69/tutorial_2LatSeqCBC1_8cc-example.html", null ],
    [ "tutorial/LatSeqExhaustive.cc", "d1/dc7/tutorial_2LatSeqExhaustive_8cc-example.html", null ],
    [ "tutorial/LatSeqKorobov.cc", "d4/dcc/tutorial_2LatSeqKorobov_8cc-example.html", null ],
    [ "tutorial/LatSeqRandom.cc", "d4/d4e/tutorial_2LatSeqRandom_8cc-example.html", null ],
    [ "tutorial/MeritSeqCBC.cc", "d1/d06/tutorial_2MeritSeqCBC_8cc-example.html", null ],
    [ "tutorial/MeritSeqCBCSignals.cc", "d9/dd5/tutorial_2MeritSeqCBCSignals_8cc-example.html", null ],
    [ "tutorial/MeritSeqCoordUniform.cc", "d0/d78/tutorial_2MeritSeqCoordUniform_8cc-example.html", null ],
    [ "tutorial/MeritSeqFastCBC.cc", "d9/d08/tutorial_2MeritSeqFastCBC_8cc-example.html", null ],
    [ "tutorial/MeritSeqNonCBC.cc", "d8/df8/tutorial_2MeritSeqNonCBC_8cc-example.html", null ],
    [ "tutorial/NetDef.cc", "d0/dcd/tutorial_2NetDef_8cc-example.html", null ],
    [ "tutorial/NetEval.cc", "d7/de3/tutorial_2NetEval_8cc-example.html", null ],
    [ "tutorial/NetFigures.cc", "d7/d3e/tutorial_2NetFigures_8cc-example.html", null ],
    [ "tutorial/NetQuantiles.cc", "de/dfd/tutorial_2NetQuantiles_8cc-example.html", null ],
    [ "tutorial/NetSearchCBC.cc", "d9/db3/tutorial_2NetSearchCBC_8cc-example.html", null ],
    [ "tutorial/NetSearchExhaustive.cc", "d5/df1/tutorial_2NetSearchExhaustive_8cc-example.html", null ],
    [ "tutorial/NetSearchRandom.cc", "d8/d1e/tutorial_2NetSearchRandom_8cc-example.html", null ],
    [ "tutorial/Storage.cc", "d9/d8a/tutorial_2Storage_8cc-example.html", null ],
    [ "tutorial/TextStream.cc", "d6/d3c/tutorial_2TextStream_8cc-example.html", null ],
    [ "tutorial/WeightedFigureOfMerit.cc", "d8/d01/tutorial_2WeightedFigureOfMerit_8cc-example.html", null ],
    [ "tutorial/WeightedFigureOfMeritCBC.cc", "d3/dd3/tutorial_2WeightedFigureOfMeritCBC_8cc-example.html", null ],
    [ "tutorial/WeightedFigureOfMeritSignals.cc", "d0/d91/tutorial_2WeightedFigureOfMeritSignals_8cc-example.html", null ]
];