LatNet Builder Manual: NetBuilder::FigureOfMerit::TValueProjMerit< EmbeddingType::MULTILEVEL, METHOD > Class Template Reference
NetBuilder::FigureOfMerit::TValueProjMerit< EmbeddingType::MULTILEVEL, METHOD > Class Template Reference
Template specialization of the projection-dependent merit defined by the t-value of the projection in the case of multilevel nets.
#include <TValueProjMerit.h>
Inherited by NetBuilder::FigureOfMerit::TValueTransformedProjMerit< EmbeddingType::MULTILEVEL, METHOD >.
Public Types
typedef std::unique_ptr< LevelCombiner::LevelCombiner > pCombiner
typedef std::vector< unsigned int > Merit
Type of the merit value.
typedef std::vector< unsigned int > SubProjCombination
Type of the subprojection combination of merit.
Public Member Functions
TValueProjMerit (unsigned int maxCardinal, pCombiner combiner)
Constructs a projection-dependent merit based on the resolution of projections.
unsigned int maxCardinal () const
Returns the maximum order of the subprojections to take into account.
virtual std::string format () const
Output information about the figure of merit.
std::vector< unsigned int > operator() (const AbstractDigitalNet &net, const LatticeTester::Coordinates &projection, const std::vector< unsigned int > &maxMeritsSubProj) const
Computes the projection-dependent multilevel merits of the net for the given projection.
virtual Real combine (const Merit &merits, const AbstractDigitalNet &net, const LatticeTester::Coordinates &projection)
Combines the projection-dependent multilevel merits into a single value merit.
Static Public Member Functions
static void update (Merit merit, SubProjCombination &subProjCombination)
Updates the combination of merit subProjCombination using merit.
static void setToZero (SubProjCombination &subProjCombination)
Initializes the combination of merit subProjCombination.
static unsigned int numLevels (const AbstractDigitalNet &net)
Determines the number of levels from a net.
static void resize (SubProjCombination &subProjCombination, unsigned int numLevels)
Resize the combination of merit subProjCombination to match the number of levels numLevels.
static unsigned int size (const SubProjCombination &subProjCombination)
Returns the size of the combination of merit subProjCombination.
Protected Attributes
unsigned int m_maxCardinal
pCombiner m_combiner
Detailed Description
template<typename METHOD>
class NetBuilder::FigureOfMerit::TValueProjMerit< EmbeddingType::MULTILEVEL, METHOD >
Template specialization of the projection-dependent merit defined by the t-value of the projection in the case of multilevel nets.
See also
NetBuilder::TValueProjMerit.
Constructor & Destructor Documentation
TValueProjMerit()
template<typename METHOD> NetBuilder::FigureOfMerit::TValueProjMerit< EmbeddingType::MULTILEVEL, METHOD >::TValueProjMerit (unsigned int maxCardinal, pCombiner combiner) inline
Constructs a projection-dependent merit based on the resolution of projections.
Parameters
maxCardinal Maximum order of the subprojections.
combiner Combiner used to combine multilevel merits.
References maxCardinal().
Referenced by NetBuilder::FigureOfMerit::TValueTransformedProjMerit< EmbeddingType::MULTILEVEL, METHOD >::TValueTransformedProjMerit().
Member Function Documentation
combine()
template<typename METHOD> virtual Real NetBuilder::FigureOfMerit::TValueProjMerit< EmbeddingType::MULTILEVEL, METHOD >::combine (const Merit & merits, const AbstractDigitalNet & net, const LatticeTester::Coordinates & projection) inline virtual
Combines the projection-dependent multilevel merits into a single value merit.
Parameters
merits Multilevel merits.
net Digital net.
projection Projection.
Reimplemented in NetBuilder::FigureOfMerit::TValueTransformedProjMerit< EmbeddingType::MULTILEVEL, METHOD >.
format()
template<typename METHOD> virtual std::string NetBuilder::FigureOfMerit::TValueProjMerit< EmbeddingType::MULTILEVEL, METHOD >::format () const inline virtual
Output information about the figure of merit.
Reimplemented in NetBuilder::FigureOfMerit::TValueTransformedProjMerit< EmbeddingType::MULTILEVEL, METHOD >.
operator()()
template<typename METHOD> std::vector< unsigned int > NetBuilder::FigureOfMerit::TValueProjMerit< EmbeddingType::MULTILEVEL, METHOD >::operator() (const AbstractDigitalNet & net, const LatticeTester::Coordinates & projection, const std::vector< unsigned int > & maxMeritsSubProj) const inline
Computes the projection-dependent multilevel merits of the net for the given projection.
Parameters
net is the digital net for which we want to compute the merit
projection is the projection to consider
maxMeritsSubProj is the maximal merit of the subprojections
References NetBuilder::AbstractDigitalNet::generatingMatrix().
resize()
template<typename METHOD> void NetBuilder::FigureOfMerit::TValueProjMerit< EmbeddingType::MULTILEVEL, METHOD >::resize (SubProjCombination & subProjCombination, unsigned int numLevels) inline static
Resize the combination of merit subProjCombination to match the number of levels numLevels.
Parameters
subProjCombination Combination of merit to resize.
numLevels Number of levels.
References numLevels().
setToZero()
template<typename METHOD> void NetBuilder::FigureOfMerit::TValueProjMerit< EmbeddingType::MULTILEVEL, METHOD >::setToZero (SubProjCombination & subProjCombination) inline static
Initializes the combination of merit subProjCombination.
Parameters
subProjCombination Combination of merit to initialized.
update()
template<typename METHOD> void NetBuilder::FigureOfMerit::TValueProjMerit< EmbeddingType::MULTILEVEL, METHOD >::update (Merit merit, SubProjCombination & subProjCombination) inline static
Updates the combination of merit subProjCombination using merit.
Parameters
merit Merit used to update.
subProjCombination Combination of merit to update.
The documentation for this class was generated from the following file:
include/netbuilder/FigureOfMerit/TValueProjMerit.h