LatNet Builder Manual: LatticeTester::Reducer< Int, BasInt, BasIntVec, BasIntMat, Dbl, DblVec, RedDbl, RedDblVec, RedDblMat > Class Template Reference
LatticeTester::Reducer< Int, BasInt, BasIntVec, BasIntMat, Dbl, DblVec, RedDbl, RedDblVec, RedDblMat > Class Template Reference
For a given lattice, this class implements methods to reduce its basis in the sense of Minkowski and to find the shortest non-zero vector of the lattice using pre-reductions and a branch-and-bound (BB) algorithm [17] .
#include <Reducer.h>
Public Member Functions
Reducer (IntLatticeBasis< Int, BasInt, BasIntVec, BasIntMat, Dbl, DblVec, RedDbl > &lat)
Constructor.
Reducer (const Reducer< Int, BasInt, BasIntVec, BasIntMat, Dbl, DblVec, RedDbl, RedDblVec, RedDblMat > &red)
Copy constructor.
~Reducer ()
Destructor.
Reducer< Int, BasInt, BasIntVec, BasIntMat, Dbl, DblVec, RedDbl, RedDblVec, RedDblMat > & operator= (const Reducer< Int, BasInt, BasIntVec, BasIntMat, Dbl, DblVec, RedDbl, RedDblVec, RedDblMat > &red)
Assignment operator.
void copy (const Reducer< Int, BasInt, BasIntVec, BasIntMat, Dbl, DblVec, RedDbl, RedDblVec, RedDblMat > &red)
Copies the reducer red into this object.
void transformStage3 (std::vector< std::int64_t > &z, int &k)
Method used in reductMinkowski to perform a transformation of stage 3 described in [1] .
bool calculCholeski (RedDblVec &DC2, RedDblMat &C0)
Finds a Choleski decomposition of the basis.
bool tryZ (int j, int i, int Stage, bool &smaller, const BasIntMat &WTemp)
Tries to find shorter vectors in reductMinkowski.
bool tryZ0 (int j, bool &smaller)
Tries to find a shorter vector in shortestVector.
bool shortestVector (NormType norm)
Computes the shortest non-zero vector of this lattice with respect to norm norm using branch-and-bound and the algorithm described in [17] .
bool shortestVectorDieter (NormType norm)
Similar to ShortestVector but uses the algorithm of Dieter [9], [16] .
bool redBB (int i, int d, int Stage, bool &smaller)
Tries to shorten the vectors of the primal basis using branch-and-bound, in reductMinkowski.
bool redBB0 (NormType norm)
Tries to shorten the smallest vector of the primal basis using branch-and-bound, in ShortestVector.
void preRedDieter (int d)
Performs the reductions of the preceding two methods using cyclically all values of \(i\) (only for \(i > d\) in the latter case) and stops after either MaxPreRed successful transformations have been achieved or no further reduction is possible.
void preRedDieterRandomized (int d, int seed)
Performs the reductions of the preceding two methods using cyclically all values of \(i\) (only for \(i > d\) in the latter case) and stops after either MaxPreRed successful transformations have been achieved or no further reduction is possible.
bool redDieter (NormType norm)
Finds the shortest non-zero vector using norm norm.
void redLLL (double fact, std::int64_t maxcpt, int dim)
Performs a LLL (Lenstra-Lenstra-Lovasz) basis reduction up to dimension dim with coefficient fact, which must be smaller than.
void redLLLNTL (double fact=0.999999, PrecisionType precision=QUADRUPLE, int dim=0)
Performs a LLL (Lenstra-Lenstra-Lovasz) basis reduction up to dimension dim with coefficient fact, which must be smaller than.
void redLLLNTLExact (double fact)
Performs a LLL (Lenstra-Lenstra-Lovasz) basis reduction up to dimension dim with coefficient fact, which must be smaller than.
void redBKZ (double fact=0.999999, std::int64_t blocksize=10, PrecisionType precision=QUADRUPLE, int dim=0)
Perform the BKZ (Block-Korkine-Zolotarev) basis reduction with the the coefficient fact and a block size Blocksize.
bool reductMinkowski (int d)
Reduces the current basis to a Minkowski reduced basis with respect to the Euclidean norm, assuming that the first \(d\) vectors are already reduced and sorted.
void pairwiseRedPrimal (int i, int d)
Performs pairwise reductions.
void pairwiseRedDual (int i)
Performs pairwise reductions, trying to reduce every other vector of the dual basis by adding multiples of the \(i\)-th vector.
Dbl getMinLength ()
Returns the length of the shortest basis vector in the lattice.
Dbl getMaxLength ()
Returns the length of the std::int64_test basis vector in the lattice.
void setBoundL2 (const DblVec &V, int dim1, int dim2)
Sets the lower bound on the square length of the shortest vector in dimension \(i\) to \(V[i]\), for \(i\) going from dim1 to dim2.
void trace (char *mess)
Debug function that print the primal and dual bases.
IntLatticeBasis< Int, BasInt, BasIntVec, BasIntMat, Dbl, DblVec, RedDbl > * getIntLatticeBasis ()
Static Public Attributes
static const std::int64_t SHORT_DIET = 1000
Whenever the number of nodes in the branch-and-bound tree exceeds SHORT_DIET in the method ShortestVector, PreRedDieterSV is automatically set to true for the next call; otherwise it is set to false.
static const std::int64_t SHORT_LLL = 1000
Whenever the number of nodes in the branch-and-bound tree exceeds SHORT_LLL in the method ShortestVector, PreRedLLLSV is automatically set to true for the next call; otherwise it is set to false.
static const std::int64_t MINK_LLL = 500000
Whenever the number of nodes in the branch-and-bound tree exceeds MINK_LLL in the method reductMinkowski, PreRedLLLRM is automatically set to true for the next call; otherwise it is set to false.
static const std::int64_t MAX_PRE_RED = 1000000
Maximum number of transformations in the method PreRedDieter.
static std::int64_t maxNodesBB = 10000000
The maximum number of nodes in the branch-and-bound tree when calling ShortestVector or reductMinkowski.
Pre-reduction flags
These boolean variables indicate which type of pre-reduction is to be performed for ShortestVector (SV) and for reductMinkowski (RM).
Dieter means the pairwise pre-reduction as in the method PreRedDieter. LLL means the LLL reduction of Lenstra, Lenstra, and Lovász. The variable PreRedDieterSV is originally set to true and the two others are originally set to false. These variables are reset automatically depending on the thresholds MinkLLL, ShortDiet, ShortLLL as explained above.
static bool PreRedDieterSV = false
static bool PreRedLLLSV = false
static bool PreRedLLLRM = false
static bool PreRedBKZ = true
Detailed Description
template<typename Int, typename BasInt, typename BasIntVec, typename BasIntMat, typename Dbl, typename DblVec, typename RedDbl, typename RedDblVec, typename RedDblMat>
class LatticeTester::Reducer< Int, BasInt, BasIntVec, BasIntMat, Dbl, DblVec, RedDbl, RedDblVec, RedDblMat >
For a given lattice, this class implements methods to reduce its basis in the sense of Minkowski and to find the shortest non-zero vector of the lattice using pre-reductions and a branch-and-bound (BB) algorithm [17] .
It also implements the method of Lenstra, Lenstra and Lovasz (LLL) [23] as well as the method of Dieter [9] to reduce a lattice basis. The Minkowski, LLL and Branch-and-bound Reduction do not need the dual lattice. Nonetheless, if a IntLatticeBasis object with a true with-dual flag is given to a Reducer, the duality will be preserve during reduction. Beside, the algorithm BKZ implemented in the NTL Library can be used as a prereduction before the Branch-and-Bound.
Constructor & Destructor Documentation
Reducer()
template<typename Int , typename BasInt , typename BasIntVec , typename BasIntMat , typename Dbl , typename DblVec , typename RedDbl , typename RedDblVec , typename RedDblMat > LatticeTester::Reducer< Int, BasInt, BasIntVec, BasIntMat, Dbl, DblVec, RedDbl, RedDblVec, RedDblMat >::Reducer (IntLatticeBasis< Int, BasInt, BasIntVec, BasIntMat, Dbl, DblVec, RedDbl > & lat)
Constructor.
Initializes the reducer to work on lattice lat.
Member Function Documentation
calculCholeski()
template<typename Int , typename BasInt , typename BasIntVec , typename BasIntMat , typename Dbl , typename DblVec , typename RedDbl , typename RedDblVec , typename RedDblMat > bool LatticeTester::Reducer< Int, BasInt, BasIntVec, BasIntMat, Dbl, DblVec, RedDbl, RedDblVec, RedDblMat >::calculCholeski (RedDblVec & DC2, RedDblMat & C0)
Finds a Choleski decomposition of the basis.
Returns in C0 the elements of the upper triangular matrix of the Choleski decomposition that are above the diagonal. Returns in DC2 the squared elements of the diagonal.
References NTL::conv().
copy()
template<typename Int , typename BasInt , typename BasIntVec , typename BasIntMat , typename Dbl , typename DblVec , typename RedDbl , typename RedDblVec , typename RedDblMat > void LatticeTester::Reducer< Int, BasInt, BasIntVec, BasIntMat, Dbl, DblVec, RedDbl, RedDblVec, RedDblMat >::copy (const Reducer< Int, BasInt, BasIntVec, BasIntMat, Dbl, DblVec, RedDbl, RedDblVec, RedDblMat > & red)
Copies the reducer red into this object.
Remarks
Richard: Encore utile?
getMaxLength()
template<typename Int, typename BasInt, typename BasIntVec, typename BasIntMat, typename Dbl, typename DblVec, typename RedDbl, typename RedDblVec, typename RedDblMat> Dbl LatticeTester::Reducer< Int, BasInt, BasIntVec, BasIntMat, Dbl, DblVec, RedDbl, RedDblVec, RedDblMat >::getMaxLength () inline
Returns the length of the std::int64_test basis vector in the lattice.
Used in Beyer Test.
pairwiseRedDual()
template<typename Int , typename BasInt , typename BasIntVec , typename BasIntMat , typename Dbl , typename DblVec , typename RedDbl , typename RedDblVec , typename RedDblMat > void LatticeTester::Reducer< Int, BasInt, BasIntVec, BasIntMat, Dbl, DblVec, RedDbl, RedDblVec, RedDblMat >::pairwiseRedDual (int i)
Performs pairwise reductions, trying to reduce every other vector of the dual basis by adding multiples of the \(i\)-th vector.
That may change the \(i\)-th vector in the primal basis. Each such dual reduction is actually performed only if that does not increase the length of vector \(i\) in the primal basis. Always uses the Euclidean norm.
References NTL::conv(), and LatticeTester::ModifVect().
pairwiseRedPrimal()
template<typename Int , typename BasInt , typename BasIntVec , typename BasIntMat , typename Dbl , typename DblVec , typename RedDbl , typename RedDblVec , typename RedDblMat > void LatticeTester::Reducer< Int, BasInt, BasIntVec, BasIntMat, Dbl, DblVec, RedDbl, RedDblVec, RedDblMat >::pairwiseRedPrimal (int i, int d)
Performs pairwise reductions.
This method tries to reduce each basis vector with index larger than \(d\) and distinct from \(i\) by adding to it a multiple of the \(i\)-th vector. Always uses the Euclidean norm.
References NTL::conv(), and LatticeTester::ModifVect().
preRedDieter()
template<typename Int , typename BasInt , typename BasIntVec , typename BasIntMat , typename Dbl , typename DblVec , typename RedDbl , typename RedDblVec , typename RedDblMat > void LatticeTester::Reducer< Int, BasInt, BasIntVec, BasIntMat, Dbl, DblVec, RedDbl, RedDblVec, RedDblMat >::preRedDieter (int d)
Performs the reductions of the preceding two methods using cyclically all values of \(i\) (only for \(i > d\) in the latter case) and stops after either MaxPreRed successful transformations have been achieved or no further reduction is possible.
Always use the Euclidean norm.
preRedDieterRandomized()
template<typename Int , typename BasInt , typename BasIntVec , typename BasIntMat , typename Dbl , typename DblVec , typename RedDbl , typename RedDblVec , typename RedDblMat > void LatticeTester::Reducer< Int, BasInt, BasIntVec, BasIntMat, Dbl, DblVec, RedDbl, RedDblVec, RedDblMat >::preRedDieterRandomized (int d, int seed)
Performs the reductions of the preceding two methods using cyclically all values of \(i\) (only for \(i > d\) in the latter case) and stops after either MaxPreRed successful transformations have been achieved or no further reduction is possible.
Always use the Euclidean norm. The choice of i is randomized.
redBKZ()
template<typename Int , typename BasInt , typename BasIntVec , typename BasIntMat , typename Dbl , typename DblVec , typename RedDbl , typename RedDblVec , typename RedDblMat > void LatticeTester::Reducer< Int, BasInt, BasIntVec, BasIntMat, Dbl, DblVec, RedDbl, RedDblVec, RedDblMat >::redBKZ (double fact = 0.999999, std::int64_t blocksize = 10, PrecisionType precision = QUADRUPLE, int dim = 0)
Perform the BKZ (Block-Korkine-Zolotarev) basis reduction with the the coefficient fact and a block size Blocksize.
The precision can be given. See Const.h for further information.
References LatticeTester::Reducer< Int, BasInt, BasIntVec, BasIntMat, Dbl, DblVec, RedDbl, RedDblVec, RedDblMat >::redBKZ().
Referenced by LatticeTester::Reducer< Int, BasInt, BasIntVec, BasIntMat, Dbl, DblVec, RedDbl, RedDblVec, RedDblMat >::redBKZ().
redDieter()
template<typename Int , typename BasInt , typename BasIntVec , typename BasIntMat , typename Dbl , typename DblVec , typename RedDbl , typename RedDblVec , typename RedDblMat > bool LatticeTester::Reducer< Int, BasInt, BasIntVec, BasIntMat, Dbl, DblVec, RedDbl, RedDblVec, RedDblMat >::redDieter (NormType norm)
Finds the shortest non-zero vector using norm norm.
Returns true upon success. Uses the algorithm of Dieter [9] given in Knuth [16] .
References NTL::conv(), and LatticeTester::ModifVect().
redLLL()
template<typename Int , typename BasInt , typename BasIntVec , typename BasIntMat , typename Dbl , typename DblVec , typename RedDbl , typename RedDblVec , typename RedDblMat > void LatticeTester::Reducer< Int, BasInt, BasIntVec, BasIntMat, Dbl, DblVec, RedDbl, RedDblVec, RedDblMat >::redLLL (double fact, std::int64_t maxcpt, int dim)
Performs a LLL (Lenstra-Lenstra-Lovasz) basis reduction up to dimension dim with coefficient fact, which must be smaller than.
If fact is closer to 1, the basis will be (typically) "more reduced", but that will require more work. The reduction algorithm is applied until maxcpt successful transformations have been done. Always uses the Euclidean norm.
redLLLNTL()
template<typename Int , typename BasInt , typename BasIntVec , typename BasIntMat , typename Dbl , typename DblVec , typename RedDbl , typename RedDblVec , typename RedDblMat > void LatticeTester::Reducer< Int, BasInt, BasIntVec, BasIntMat, Dbl, DblVec, RedDbl, RedDblVec, RedDblMat >::redLLLNTL (double fact = 0.999999, PrecisionType precision = QUADRUPLE, int dim = 0)
Performs a LLL (Lenstra-Lenstra-Lovasz) basis reduction up to dimension dim with coefficient fact, which must be smaller than.
If fact is closer to 1, the basis will be (typically) "more reduced", but that will require more work. The reduction algorithm is applied until maxcpt successful transformations have been done. Always uses the Euclidean norm. This version is implemented in the NTL Library with approximate number with arbitrary precision. The precision can be given. See Const.h for further information.
References LatticeTester::Reducer< Int, BasInt, BasIntVec, BasIntMat, Dbl, DblVec, RedDbl, RedDblVec, RedDblMat >::redLLLNTL().
Referenced by LatticeTester::Reducer< Int, BasInt, BasIntVec, BasIntMat, Dbl, DblVec, RedDbl, RedDblVec, RedDblMat >::redLLLNTL().
redLLLNTLExact()
template<typename Int , typename BasInt , typename BasIntVec , typename BasIntMat , typename Dbl , typename DblVec , typename RedDbl , typename RedDblVec , typename RedDblMat > void LatticeTester::Reducer< Int, BasInt, BasIntVec, BasIntMat, Dbl, DblVec, RedDbl, RedDblVec, RedDblMat >::redLLLNTLExact (double fact)
Performs a LLL (Lenstra-Lenstra-Lovasz) basis reduction up to dimension dim with coefficient fact, which must be smaller than.
If fact is closer to 1, the basis will be (typically) "more reduced", but that will require more work. The reduction algorithm is applied until maxcpt successful transformations have been done. Always uses the Euclidean norm. This version is implemented in the NTL Library with exact number (arbitrary precision RR)
reductMinkowski()
template<typename Int , typename BasInt , typename BasIntVec , typename BasIntMat , typename Dbl , typename DblVec , typename RedDbl , typename RedDblVec , typename RedDblMat > bool LatticeTester::Reducer< Int, BasInt, BasIntVec, BasIntMat, Dbl, DblVec, RedDbl, RedDblVec, RedDblMat >::reductMinkowski (int d)
Reduces the current basis to a Minkowski reduced basis with respect to the Euclidean norm, assuming that the first \(d\) vectors are already reduced and sorted.
If MaxNodesBB is exceeded during one of the branch-and-bound step, the method aborts and returns false. Otherwise it returns true, the basis is reduced and sorted by vector lengths (the shortest vector is V[0] and the std::int64_test is V[Dim-1]).
shortestVector()
template<typename Int , typename BasInt , typename BasIntVec , typename BasIntMat , typename Dbl , typename DblVec , typename RedDbl , typename RedDblVec , typename RedDblMat > bool LatticeTester::Reducer< Int, BasInt, BasIntVec, BasIntMat, Dbl, DblVec, RedDbl, RedDblVec, RedDblMat >::shortestVector (NormType norm)
Computes the shortest non-zero vector of this lattice with respect to norm norm using branch-and-bound and the algorithm described in [17] .
The Norm member of this object will be changed to norm. If MaxNodesBB is exceeded during one of the branch-and-bounds, the method aborts and returns false. Otherwise, it returns true. Uses the pre-reduction algorithms of Dieter and of Lenstra-Lenstra-Lovasz. Advice: must perform pre-reduction before using this Branch-and-Bound method on high dimension basis.
transformStage3()
template<typename Int , typename BasInt , typename BasIntVec , typename BasIntMat , typename Dbl , typename DblVec , typename RedDbl , typename RedDblVec , typename RedDblMat > void LatticeTester::Reducer< Int, BasInt, BasIntVec, BasIntMat, Dbl, DblVec, RedDbl, RedDblVec, RedDblMat >::transformStage3 (std::vector< std::int64_t > & z, int & k)
Method used in reductMinkowski to perform a transformation of stage 3 described in [1] .
Also used in ShortestVector. Assumes that \(\sum_{i=1}^t z_i V_i\) is a short vector that will enter the basis. Tries to reduce some vectors by looking for indices \(i < j\) such that \(|z_j| > 1\) and \(q=\lfloor z_i/z_j\rfloor\not0\), and adding \(q V_i\) to \(V_j\) when this happens. Returns in \(k\) the last index \(j\) such that \(|z_j|=1\).
References LatticeTester::ModifVect().
Member Data Documentation
MAX_PRE_RED
template<typename Int, typename BasInt, typename BasIntVec, typename BasIntMat, typename Dbl, typename DblVec, typename RedDbl, typename RedDblVec, typename RedDblMat> const std::int64_t LatticeTester::Reducer< Int, BasInt, BasIntVec, BasIntMat, Dbl, DblVec, RedDbl, RedDblVec, RedDblMat >::MAX_PRE_RED = 1000000 static
Maximum number of transformations in the method PreRedDieter.
After MAX_PRE_RED successful transformations have been performed, the prereduction is stopped.
maxNodesBB
template<typename Int, typename BasInt, typename BasIntVec, typename BasIntMat, typename Dbl, typename DblVec, typename RedDbl, typename RedDblVec, typename RedDblMat> std::int64_t LatticeTester::Reducer< Int, BasInt, BasIntVec, BasIntMat, Dbl, DblVec, RedDbl, RedDblVec, RedDblMat >::maxNodesBB = 10000000 static
The maximum number of nodes in the branch-and-bound tree when calling ShortestVector or reductMinkowski.
When this number is exceeded, the method aborts and returns false.
The documentation for this class was generated from the following file:
latticetester/include/latticetester/Reducer.h