var searchData=
[
  ['saving_20the_20results_20in_20a_20folder_0',['Saving the results in a folder',['../d0/da5/cmdtut_quickrecipes.html#cmdtut_quickrecipes_outputfolder',1,'']]],
  ['search_20space_20with_20other_20methods_1',['Exploring the search space with other methods',['../d0/da5/cmdtut_quickrecipes.html#cmdtut_quickrecipes_explorations',1,'']]],
  ['search_20tasks_2',['Search tasks',['../d5/d09/libtut_net_tasks.html#libtut_net_tasks_search',1,'']]],
  ['searches_3',['searches',['../d5/d09/libtut_net_tasks.html#libtut_net_tasks_search_cbc',1,'CBC searches'],['../d5/d09/libtut_net_tasks.html#libtut_net_tasks_search_exhaustive',1,'Exhaustive searches'],['../d5/d09/libtut_net_tasks.html#libtut_net_tasks_search_random',1,'Random searches']]],
  ['sequence_4',['Sequence',['../da/d2e/libtut_impl.html#libtut_impl_bridgeseq',1,'Bridge Sequence'],['../da/d2e/libtut_impl.html#libtut_impl_seq',1,'Sequence']]],
  ['sequences_5',['Sequences',['../d5/d48/libtut_lat_latseq.html#libtut_lat_latseq_cbc',1,'Component-by-Component Sequences'],['../d5/d48/libtut_lat_latseq.html#libtut_lat_latseq_exhaustive',1,'Exhaustive Sequences'],['../d5/d48/libtut_lat_latseq.html#libtut_lat_latseq_korobov',1,'Korobov Sequences'],['../d5/d48/libtut_lat_latseq.html#libtut_lat_latseq_random',1,'Random Sequences'],['../dd/df1/libtut_lat_genseq.html#libtut_lat_genseq_vector',1,'Vectors of Integer/Polynomial Sequences']]],
  ['sequences_20of_20generator_20values_6',['Sequences of Generator Values',['../dd/df1/libtut_lat_genseq.html',1,'libtut_lat']]],
  ['sequences_20of_20lattice_20definitions_7',['Sequences of Lattice Definitions',['../d5/d48/libtut_lat_latseq.html',1,'libtut_lat']]],
  ['sequences_20of_20merit_20values_8',['Sequences of Merit Values',['../da/dd0/libtut_lat_meritseq.html',1,'libtut_lat']]],
  ['set_9',['Evaluating figures of merit for a specific point set',['../d0/da5/cmdtut_quickrecipes.html#cmdtut_quickrecipes_eval',1,'']]],
  ['set_20types_10',['set types',['../d2/d6f/cmdtut_advanced_pointsets.html',1,'Point set types'],['../dc/d5a/feats_pointsets.html',1,'Point set types'],['../d2/d6f/cmdtut_advanced_pointsets.html#cmdtut_advanced_pointsets_types',1,'Switching between point set types']]],
  ['sets_11',['sets',['../d0/da5/cmdtut_quickrecipes.html#cmdtut_quickrecipes_embedded',1,'Constructing embedded point sets'],['../d0/da5/cmdtut_quickrecipes.html#cmdtut_quickrecipes_extend',1,'Extending point sets'],['../dc/de0/cmdtut_advanced_output_style.html#cmdtut_advanced_output_style_interlaced',1,'Interlaced point sets'],['../df/df1/cmdtut_advanced_multilevel.html',1,'Multilevel point sets'],['../d6/d6f/feats_multilevel.html',1,'Multilevel point sets'],['../d9/d80/feats_filters.html#feats_filters_multilevel',1,'Normalizations and filters for multilevel point sets']]],
  ['signals_12',['Signals',['../df/d4b/libtut_lat_figures.html#libtut_lat_figures_signals',1,'A Improved Example Using Signals'],['../da/dd0/libtut_lat_meritseq.html#libtut_lat_meritseq_cbc_signals',1,'CBC Construction Using Signals']]],
  ['simple_20example_13',['A Simple Example',['../df/d4b/libtut_lat_figures.html#libtut_lat_figures_simple',1,'']]],
  ['simple_20example_20using_20cbc_20construction_14',['A Simple Example Using CBC Construction',['../df/d4b/libtut_lat_figures.html#libtut_lat_figures_cbc_simple',1,'']]],
  ['simplified_20sobol_20format_15',['Simplified Sobol format',['../dc/de0/cmdtut_advanced_output_style.html#cmdtut_advanced_output_style_sobol_sobol',1,'']]],
  ['size_20and_20modulus_20of_20lattice_20rules_16',['Size and modulus of lattice rules',['../d2/d6f/cmdtut_advanced_pointsets.html#cmdtut_advanced_pointsets_lat_size',1,'']]],
  ['size_20of_20digital_20nets_17',['Size of digital nets',['../d2/d6f/cmdtut_advanced_pointsets.html#cmdtut_advanced_pointsets_net_size',1,'']]],
  ['sobol_20construction_18',['Sobol construction',['../dc/d5a/feats_pointsets.html#feats_pointsets_net_sobol',1,'Sobol' construction'],['../dc/ded/libtut_net_def.html#libtut_net_def_sobol',1,'Sobol' construction']]],
  ['sobol_20digital_20nets_19',['Formats for Sobol digital nets',['../dc/de0/cmdtut_advanced_output_style.html#cmdtut_advanced_output_style_sobol',1,'']]],
  ['sobol_20format_20',['Simplified Sobol format',['../dc/de0/cmdtut_advanced_output_style.html#cmdtut_advanced_output_style_sobol_sobol',1,'']]],
  ['space_20with_20other_20methods_21',['Exploring the search space with other methods',['../d0/da5/cmdtut_quickrecipes.html#cmdtut_quickrecipes_explorations',1,'']]],
  ['specific_20lattice_20rule_22',['How to construct a specific lattice rule',['../d2/d6f/cmdtut_advanced_pointsets.html#cmdtut_advanced_pointsets_lat_specify',1,'']]],
  ['specific_20net_23',['How to construct a specific net',['../d2/d6f/cmdtut_advanced_pointsets.html#cmdtut_advanced_pointsets_net_specify',1,'']]],
  ['specific_20point_20set_24',['Evaluating figures of merit for a specific point set',['../d0/da5/cmdtut_quickrecipes.html#cmdtut_quickrecipes_eval',1,'']]],
  ['standard_25',['Usage of the C++14 Standard',['../da/d2e/libtut_impl.html#libtut_impl_cpp11',1,'']]],
  ['static_20polymorphism_26',['Static Polymorphism',['../da/d2e/libtut_impl.html#libtut_impl_polymorphism',1,'']]],
  ['storage_27',['Storage',['../df/d4b/libtut_lat_figures.html#libtut_lat_figures_storage',1,'']]],
  ['styles_28',['Output styles',['../dc/de0/cmdtut_advanced_output_style.html',1,'cmdtut_spec']]],
  ['summary_20of_20available_20formats_29',['Summary of available formats',['../dc/de0/cmdtut_advanced_output_style.html#cmdtut_advanced_output_style_summary',1,'']]],
  ['summary_20of_20command_20line_20options_30',['Summary of Command-Line Options',['../de/db5/cmdtut_summary.html',1,'cmdtut']]],
  ['switching_20between_20point_20set_20types_31',['Switching between point set types',['../d2/d6f/cmdtut_advanced_pointsets.html#cmdtut_advanced_pointsets_types',1,'']]]
];
