var searchData=
[
  ['fast_20cbc_20construction_0',['Fast CBC Construction',['../da/dd0/libtut_lat_meritseq.html#libtut_lat_meritseq_fastcbc',1,'']]],
  ['features_1',['Main features',['../dd/d51/feats.html',1,'index']]],
  ['fftw_2',['Usage of FFTW',['../da/d2e/libtut_impl.html#libtut_impl_fftw',1,'']]],
  ['figures_20of_20merit_3',['Figures of Merit',['../da/dd0/libtut_lat_meritseq.html#libtut_lat_meritseq_coorduni',1,'CBC Construction for Coordinate-Uniform Figures of Merit'],['../df/d4b/libtut_lat_figures.html',1,'Weighted Figures of Merit']]],
  ['figures_20of_20merit_4',['Figures of merit',['../d3/d8e/cmdtut_advanced_figures.html',1,'Figures of merit'],['../d6/d4c/feats_figures.html',1,'Figures of merit'],['../d4/d66/libtut_net_figures.html',1,'Figures of merit']]],
  ['figures_20of_20merit_5',['Using different figures of merit',['../d0/da5/cmdtut_quickrecipes.html#cmdtut_quickrecipes_figures',1,'']]],
  ['figures_20of_20merit_20for_20a_20specific_20point_20set_6',['Evaluating figures of merit for a specific point set',['../d0/da5/cmdtut_quickrecipes.html#cmdtut_quickrecipes_eval',1,'']]],
  ['figures_20of_20merit_20for_20digital_20nets_7',['Figures of merit for digital nets',['../d1/d27/feats_figures_net.html',1,'feats_figures']]],
  ['figures_20of_20merit_20for_20interlaced_20digital_20nets_8',['Figures of merit for interlaced digital nets',['../d1/d27/feats_figures_net.html#feats_figures_net_interlaced',1,'']]],
  ['figures_20of_20merit_20for_20interlaced_20polynomial_20lattice_20rules_9',['Figures of merit for interlaced polynomial lattice rules',['../d3/dc5/feats_figures_lat.html#feats_figures_lat_interlaced',1,'']]],
  ['figures_20of_20merit_20for_20ordinary_20lattice_20rules_10',['Figures of merit for ordinary lattice rules',['../d3/dc5/feats_figures_lat.html#feats_figures_lat_ord',1,'']]],
  ['figures_20of_20merit_20for_20polynomial_20lattice_20rules_11',['Figures of merit for polynomial lattice rules',['../d3/dc5/feats_figures_lat.html#feats_figures_lat_poly',1,'']]],
  ['figures_20of_20merit_20for_20rank_201_20lattices_12',['Figures of merit for rank-1 lattices',['../d3/dc5/feats_figures_lat.html',1,'feats_figures']]],
  ['filtered_20random_20cbc_13',['Filtered Random CBC',['../dd/dd9/libtut_lat_filters.html#libtut_lat_filters_rcbc_signals',1,'']]],
  ['filters_14',['Filters',['../d2/d15/cmdtut_advanced_filters.html#cmdtut_advanced_filters_filters',1,'']]],
  ['filters_15',['Normalizations and filters',['../d9/d80/feats_filters.html',1,'feats']]],
  ['filters_20and_20combiners_16',['Filters and Combiners',['../dd/dd9/libtut_lat_filters.html',1,'libtut_lat']]],
  ['filters_20and_20normalizations_17',['Filters and normalizations',['../d2/d15/cmdtut_advanced_filters.html',1,'cmdtut_spec']]],
  ['filters_20and_20normalizations_18',['filters and normalizations',['../d0/da5/cmdtut_quickrecipes.html#cmdtut_quickrecipes_filters',1,'Applying filters and normalizations'],['../d2/d15/cmdtut_advanced_filters.html#cmdtut_advanced_filters_multilevel',1,'Using multilevel filters and normalizations']]],
  ['filters_20for_20multilevel_20point_20sets_19',['Normalizations and filters for multilevel point sets',['../d9/d80/feats_filters.html#feats_filters_multilevel',1,'']]],
  ['first_20example_20',['A first example',['../d0/da5/cmdtut_quickrecipes.html#cmdtut_quickrecipes_first_example',1,'']]],
  ['folder_21',['Saving the results in a folder',['../d0/da5/cmdtut_quickrecipes.html#cmdtut_quickrecipes_outputfolder',1,'']]],
  ['for_20a_20specific_20point_20set_22',['Evaluating figures of merit for a specific point set',['../d0/da5/cmdtut_quickrecipes.html#cmdtut_quickrecipes_eval',1,'']]],
  ['for_20coordinate_20uniform_20figures_20of_20merit_23',['CBC Construction for Coordinate-Uniform Figures of Merit',['../da/dd0/libtut_lat_meritseq.html#libtut_lat_meritseq_coorduni',1,'']]],
  ['for_20digital_20nets_24',['Figures of merit for digital nets',['../d1/d27/feats_figures_net.html',1,'feats_figures']]],
  ['for_20interlaced_20digital_20nets_25',['Figures of merit for interlaced digital nets',['../d1/d27/feats_figures_net.html#feats_figures_net_interlaced',1,'']]],
  ['for_20interlaced_20polynomial_20lattice_20rules_26',['Figures of merit for interlaced polynomial lattice rules',['../d3/dc5/feats_figures_lat.html#feats_figures_lat_interlaced',1,'']]],
  ['for_20multilevel_20point_20sets_27',['Normalizations and filters for multilevel point sets',['../d9/d80/feats_filters.html#feats_filters_multilevel',1,'']]],
  ['for_20ordinary_20lattice_20rules_28',['Figures of merit for ordinary lattice rules',['../d3/dc5/feats_figures_lat.html#feats_figures_lat_ord',1,'']]],
  ['for_20polynomial_20lattice_20rules_29',['for polynomial lattice rules',['../da/d25/feats_poly.html',1,'Detailed guidelines for polynomial lattice rules'],['../d3/dc5/feats_figures_lat.html#feats_figures_lat_poly',1,'Figures of merit for polynomial lattice rules']]],
  ['for_20rank_201_20lattices_30',['Figures of merit for rank-1 lattices',['../d3/dc5/feats_figures_lat.html',1,'feats_figures']]],
  ['for_20sobol_20digital_20nets_31',['Formats for Sobol digital nets',['../dc/de0/cmdtut_advanced_output_style.html#cmdtut_advanced_output_style_sobol',1,'']]],
  ['format_32',['format',['../dc/de0/cmdtut_advanced_output_style.html#cmdtut_advanced_output_style_sobol_jk',1,'Joe &amp; Kuo format'],['../dc/de0/cmdtut_advanced_output_style.html#cmdtut_advanced_output_style_lattice',1,'Lattice format'],['../dc/de0/cmdtut_advanced_output_style.html#cmdtut_advanced_output_style_net',1,'Net format'],['../dc/de0/cmdtut_advanced_output_style.html#cmdtut_advanced_output_style_sobol_sobol',1,'Simplified Sobol format']]],
  ['formats_33',['Summary of available formats',['../dc/de0/cmdtut_advanced_output_style.html#cmdtut_advanced_output_style_summary',1,'']]],
  ['formats_20for_20sobol_20digital_20nets_34',['Formats for Sobol digital nets',['../dc/de0/cmdtut_advanced_output_style.html#cmdtut_advanced_output_style_sobol',1,'']]],
  ['fullcbcexplorer_35',['FullCBCExplorer',['../d5/d09/libtut_net_tasks.html#libtut_net_tasks_search_cbc_full',1,'']]]
];
