var searchData=
[
  ['of_20available_20formats_0',['Summary of available formats',['../dc/de0/cmdtut_advanced_output_style.html#cmdtut_advanced_output_style_summary',1,'']]],
  ['of_20command_20line_20options_1',['Summary of Command-Line Options',['../de/db5/cmdtut_summary.html',1,'cmdtut']]],
  ['of_20digital_20nets_2',['Size of digital nets',['../d2/d6f/cmdtut_advanced_pointsets.html#cmdtut_advanced_pointsets_net_size',1,'']]],
  ['of_20fftw_3',['Usage of FFTW',['../da/d2e/libtut_impl.html#libtut_impl_fftw',1,'']]],
  ['of_20generator_20values_4',['Sequences of Generator Values',['../dd/df1/libtut_lat_genseq.html',1,'libtut_lat']]],
  ['of_20integer_20polynomial_20sequences_5',['Vectors of Integer/Polynomial Sequences',['../dd/df1/libtut_lat_genseq.html#libtut_lat_genseq_vector',1,'']]],
  ['of_20lattice_20definitions_6',['Sequences of Lattice Definitions',['../d5/d48/libtut_lat_latseq.html',1,'libtut_lat']]],
  ['of_20lattice_20rules_7',['of lattice rules',['../d2/d6f/cmdtut_advanced_pointsets.html#cmdtut_advanced_pointsets_lat_size',1,'Size and modulus of lattice rules'],['../d2/d6f/cmdtut_advanced_pointsets.html#cmdtut_advanced_pointsets_lat_construction',1,'Types of lattice rules']]],
  ['of_20latticetester_8',['Usage of LatticeTester',['../da/d2e/libtut_impl.html#libtut_impl_latticetester',1,'']]],
  ['of_20merit_9',['of Merit',['../da/dd0/libtut_lat_meritseq.html#libtut_lat_meritseq_coorduni',1,'CBC Construction for Coordinate-Uniform Figures of Merit'],['../df/d4b/libtut_lat_figures.html',1,'Weighted Figures of Merit']]],
  ['of_20merit_10',['of merit',['../d3/d8e/cmdtut_advanced_figures.html',1,'Figures of merit'],['../d6/d4c/feats_figures.html',1,'Figures of merit'],['../d4/d66/libtut_net_figures.html',1,'Figures of merit'],['../d0/da5/cmdtut_quickrecipes.html#cmdtut_quickrecipes_figures',1,'Using different figures of merit']]],
  ['of_20merit_20for_20a_20specific_20point_20set_11',['Evaluating figures of merit for a specific point set',['../d0/da5/cmdtut_quickrecipes.html#cmdtut_quickrecipes_eval',1,'']]],
  ['of_20merit_20for_20digital_20nets_12',['Figures of merit for digital nets',['../d1/d27/feats_figures_net.html',1,'feats_figures']]],
  ['of_20merit_20for_20interlaced_20digital_20nets_13',['Figures of merit for interlaced digital nets',['../d1/d27/feats_figures_net.html#feats_figures_net_interlaced',1,'']]],
  ['of_20merit_20for_20interlaced_20polynomial_20lattice_20rules_14',['Figures of merit for interlaced polynomial lattice rules',['../d3/dc5/feats_figures_lat.html#feats_figures_lat_interlaced',1,'']]],
  ['of_20merit_20for_20ordinary_20lattice_20rules_15',['Figures of merit for ordinary lattice rules',['../d3/dc5/feats_figures_lat.html#feats_figures_lat_ord',1,'']]],
  ['of_20merit_20for_20polynomial_20lattice_20rules_16',['Figures of merit for polynomial lattice rules',['../d3/dc5/feats_figures_lat.html#feats_figures_lat_poly',1,'']]],
  ['of_20merit_20for_20rank_201_20lattices_17',['Figures of merit for rank-1 lattices',['../d3/dc5/feats_figures_lat.html',1,'feats_figures']]],
  ['of_20merit_20values_18',['of Merit Values',['../d9/d28/libtut_lat_misc.html#libtut_lat_quantiles',1,'Examining the Distribution of Merit Values'],['../da/dd0/libtut_lat_meritseq.html',1,'Sequences of Merit Values']]],
  ['of_20normalizations_19',['List of normalizations',['../d9/d80/feats_filters.html#feats_filters_norms',1,'']]],
  ['of_20ntl_20',['Usage of NTL',['../da/d2e/libtut_impl.html#libtut_impl_ntl',1,'']]],
  ['of_20points_21',['Extension of the Number of Points',['../dd/df1/libtut_lat_genseq.html#libtut_lat_genseq_extend',1,'']]],
  ['of_20polynomials_22',['Implementation of Polynomials',['../d4/d56/libtut_lat_polynomial.html',1,'libtut_lat']]],
  ['of_20the_20boost_20c_20libraries_23',['Usage of the Boost C++ Libraries',['../da/d2e/libtut_impl.html#libtut_impl_boost',1,'']]],
  ['of_20the_20c_2014_20standard_24',['Usage of the C++14 Standard',['../da/d2e/libtut_impl.html#libtut_impl_cpp11',1,'']]],
  ['of_20the_20number_20of_20points_25',['Extension of the Number of Points',['../dd/df1/libtut_lat_genseq.html#libtut_lat_genseq_extend',1,'']]],
  ['on_20basis_20construction_26',['A note on basis construction',['../d0/d18/classLatticeTester_1_1BasisConstruction.html#autotoc_md0',1,'']]],
  ['options_27',['Summary of Command-Line Options',['../de/db5/cmdtut_summary.html',1,'cmdtut']]],
  ['order_20dependent_20weights_28',['Order-Dependent Weights',['../df/d36/cmdtut_advanced_weights.html#cmdtut_advanced_weights_orderdep',1,'']]],
  ['ordinary_20lattice_20rules_29',['Figures of merit for ordinary lattice rules',['../d3/dc5/feats_figures_lat.html#feats_figures_lat_ord',1,'']]],
  ['ordinary_20lattices_30',['Ordinary lattices',['../dc/d5a/feats_pointsets.html#feats_pointsets_latrank1_ord',1,'']]],
  ['other_20examples_31',['Other Examples',['../d9/d28/libtut_lat_misc.html',1,'libtut_lat']]],
  ['other_20methods_32',['Exploring the search space with other methods',['../d0/da5/cmdtut_quickrecipes.html#cmdtut_quickrecipes_explorations',1,'']]],
  ['outline_33',['Manual Outline',['../index.html#outline',1,'']]],
  ['output_34',['Text Output',['../d6/d44/libtut_lat_textstream.html',1,'libtut_lat']]],
  ['output_20styles_35',['Output styles',['../dc/de0/cmdtut_advanced_output_style.html',1,'cmdtut_spec']]],
  ['overview_36',['Overview',['../index.html#overview',1,'']]]
];
