LatNet Builder Manual: NetBuilder::FigureOfMerit::TValueTransformedProjMerit< EmbeddingType::MULTILEVEL, METHOD > Class Template Reference
NetBuilder::FigureOfMerit::TValueTransformedProjMerit< EmbeddingType::MULTILEVEL, METHOD > Class Template Reference
Template specialization of the projection-dependent merit defined by the t-value of the projection in the case of multilevel nets.
#include <TValueTransformedProjMerit.h>
Inherits NetBuilder::FigureOfMerit::TValueProjMerit< ET, METHOD >, and NetBuilder::FigureOfMerit::TValueProjMerit< EmbeddingType::MULTILEVEL, METHOD >.
Public Types
typedef std::vector< unsigned int > Merit
Type of the merit value.
typedef std::unique_ptr< LevelCombiner::LevelCombiner > pCombiner
Public Types inherited from NetBuilder::FigureOfMerit::TValueProjMerit< EmbeddingType::MULTILEVEL, METHOD >
typedef std::unique_ptr< LevelCombiner::LevelCombiner > pCombiner
typedef std::vector< unsigned int > Merit
Type of the merit value.
typedef std::vector< unsigned int > SubProjCombination
Type of the subprojection combination of merit.
Public Member Functions
TValueTransformedProjMerit (unsigned int maxCardinal, pCombiner combiner, int cost_function)
Constructs a transformed projection-dependent merit based on the t-value of projections.
virtual Real combine (const Merit &merits, const AbstractDigitalNet &net, const LatticeTester::Coordinates &projection)
Combines the projection-dependent multilevel merits into a single value merit.
virtual std::string format () const
Output information about the figure of merit.
Public Member Functions inherited from NetBuilder::FigureOfMerit::TValueProjMerit< EmbeddingType::MULTILEVEL, METHOD >
TValueProjMerit (unsigned int maxCardinal, pCombiner combiner)
Constructs a projection-dependent merit based on the resolution of projections.
unsigned int maxCardinal () const
Returns the maximum order of the subprojections to take into account.
std::vector< unsigned int > operator() (const AbstractDigitalNet &net, const LatticeTester::Coordinates &projection, const std::vector< unsigned int > &maxMeritsSubProj) const
Computes the projection-dependent multilevel merits of the net for the given projection.
Additional Inherited Members
Static Public Member Functions inherited from NetBuilder::FigureOfMerit::TValueProjMerit< EmbeddingType::MULTILEVEL, METHOD >
static void update (Merit merit, SubProjCombination &subProjCombination)
Updates the combination of merit subProjCombination using merit.
static void setToZero (SubProjCombination &subProjCombination)
Initializes the combination of merit subProjCombination.
static unsigned int numLevels (const AbstractDigitalNet &net)
Determines the number of levels from a net.
static void resize (SubProjCombination &subProjCombination, unsigned int numLevels)
Resize the combination of merit subProjCombination to match the number of levels numLevels.
static unsigned int size (const SubProjCombination &subProjCombination)
Returns the size of the combination of merit subProjCombination.
Protected Attributes inherited from NetBuilder::FigureOfMerit::TValueProjMerit< EmbeddingType::MULTILEVEL, METHOD >
unsigned int m_maxCardinal
pCombiner m_combiner
Detailed Description
template<typename METHOD>
class NetBuilder::FigureOfMerit::TValueTransformedProjMerit< EmbeddingType::MULTILEVEL, METHOD >
Template specialization of the projection-dependent merit defined by the t-value of the projection in the case of multilevel nets.
See also
NetBuilder::TValueProjMerit.
Constructor & Destructor Documentation
TValueTransformedProjMerit()
template<typename METHOD> NetBuilder::FigureOfMerit::TValueTransformedProjMerit< EmbeddingType::MULTILEVEL, METHOD >::TValueTransformedProjMerit (unsigned int maxCardinal, pCombiner combiner, int cost_function) inline
Constructs a transformed projection-dependent merit based on the t-value of projections.
Parameters
maxCardinal Maximum order of the subprojections.
combiner Not used. For sake of uniformity.
cost_function Identifier for the figure of merit to be used.
References NetBuilder::FigureOfMerit::TValueProjMerit< EmbeddingType::MULTILEVEL, METHOD >::maxCardinal(), and NetBuilder::FigureOfMerit::TValueProjMerit< EmbeddingType::MULTILEVEL, METHOD >::TValueProjMerit().
Member Function Documentation
combine()
template<typename METHOD> virtual Real NetBuilder::FigureOfMerit::TValueTransformedProjMerit< EmbeddingType::MULTILEVEL, METHOD >::combine (const Merit & merits, const AbstractDigitalNet & net, const LatticeTester::Coordinates & projection) inline virtual
Combines the projection-dependent multilevel merits into a single value merit.
Parameters
merits Multilevel merits.
net Digital net.
projection Projection.
Reimplemented from NetBuilder::FigureOfMerit::TValueProjMerit< EmbeddingType::MULTILEVEL, METHOD >.
References NetBuilder::AbstractDigitalNet::numColumns().
format()
template<typename METHOD> virtual std::string NetBuilder::FigureOfMerit::TValueTransformedProjMerit< EmbeddingType::MULTILEVEL, METHOD >::format () const inline virtual
Output information about the figure of merit.
Reimplemented from NetBuilder::FigureOfMerit::TValueProjMerit< EmbeddingType::MULTILEVEL, METHOD >.
The documentation for this class was generated from the following file:
include/netbuilder/FigureOfMerit/TValueTransformedProjMerit.h