LatNet Builder Manual: NetBuilder::Accumulator Class Reference
NetBuilder::Accumulator Class Reference
Accumulator class.
#include <Accumulator.h>
Public Member Functions
Accumulator (Real initialValue, Real normType)
Constructor.
Accumulator (Accumulator &)=default
Default copy constructor.
Accumulator (Accumulator &&)=default
Default move constructor.
void accumulate (Real weight, Real value, Real power)
Accumulate a new merit value value with weight weight.
Real tryAccumulate (Real weight, Real value, Real power) const
Returns the value which would be held by the accumulator if a new merit value value with weight weight were accumulated.
void set (Real value)
Set the current merit value held by the accumulator to value.
Real value () const
Returns the current merit value held by the accumulator.
Detailed Description
Accumulator class.
Used by figures of merit to aggregate partial merit values (dimension, projection-dependent, etc.).
Constructor & Destructor Documentation
Accumulator()
NetBuilder::Accumulator::Accumulator (Real initialValue, Real normType)
Constructor.
Parameters
initialValue Initial value of the accumulator.
normType Norm type of the accumulator. A finite real corresponds to the q-norm whereas the infinite corresponds to the sup norm.
Referenced by Accumulator(), and Accumulator().
Member Function Documentation
accumulate()
void NetBuilder::Accumulator::accumulate (Real weight, Real value, Real power)
Accumulate a new merit value value with weight weight.
The accumulator raises value to power power.
Parameters
weight Weight of the value.
value Value to accumulate.
power Power used when raising value.
References value().
tryAccumulate()
Real NetBuilder::Accumulator::tryAccumulate (Real weight, Real value, Real power) const
Returns the value which would be held by the accumulator if a new merit value value with weight weight were accumulated.
The accumulator raises value to power power.
Parameters
weight Weight of the value.
value Value to accumulate.
power Power used when raising value.
References value().
The documentation for this class was generated from the following file:
include/netbuilder/Helpers/Accumulator.h