LatNet Builder Manual: NetBuilder::FigureOfMerit::ResolutionGapProjMerit< EmbeddingType::UNILEVEL > Class Reference
NetBuilder::FigureOfMerit::ResolutionGapProjMerit< EmbeddingType::UNILEVEL > Class Reference
Template specialization of the projection-dependent merit defined by the resolution-gap of the projection in the case of unilevel nets.
#include <ResolutionGapProjMerit.h>
Public Types
typedef std::unique_ptr< LevelCombiner::LevelCombiner > pCombiner
Public Member Functions
ResolutionGapProjMerit (unsigned int maxCardinal, pCombiner combiner=std::make_unique< LevelCombiner::LevelCombiner >())
Constructs a projection-dependent merit based on the resolution-gap of projections.
unsigned int maxCardinal () const
Returns the maximum order of the subprojections to take into account.
std::string format () const
Output information about the figure of merit.
Real operator() (const AbstractDigitalNet &net, const LatticeTester::Coordinates &projection)
Computes the projection-dependent merit of the net net for the given projection.
CBCCoordinateSet projections (Dimension dimension) const
Returns the projections to include in the figure of merit partial computation for dimension dimension.
Detailed Description
Template specialization of the projection-dependent merit defined by the resolution-gap of the projection in the case of unilevel nets.
See also
NetBuilder::ResolutionGapProjMerit
Constructor & Destructor Documentation
ResolutionGapProjMerit()
NetBuilder::FigureOfMerit::ResolutionGapProjMerit< EmbeddingType::UNILEVEL >::ResolutionGapProjMerit (unsigned int maxCardinal, pCombiner combiner = std::make_unique<LevelCombiner::LevelCombiner>()) inline
Constructs a projection-dependent merit based on the resolution-gap of projections.
Parameters
maxCardinal Maximum order of the subprojections.
combiner Not used. For sake of uniformity.
References maxCardinal().
Member Function Documentation
operator()()
Real NetBuilder::FigureOfMerit::ResolutionGapProjMerit< EmbeddingType::UNILEVEL >::operator() (const AbstractDigitalNet & net, const LatticeTester::Coordinates & projection) inline
Computes the projection-dependent merit of the net net for the given projection.
Parameters
net Digital to evaluate.
projection Projection to use.
References NetBuilder::AbstractDigitalNet::generatingMatrix(), NetBuilder::AbstractDigitalNet::numColumns(), and NetBuilder::GeneratingMatrix::subMatrix().
projections()
CBCCoordinateSet NetBuilder::FigureOfMerit::ResolutionGapProjMerit< EmbeddingType::UNILEVEL >::projections (Dimension dimension) const inline
Returns the projections to include in the figure of merit partial computation for dimension dimension.
Parameters
dimension Dimension of the partial computation.
The documentation for this class was generated from the following file:
include/netbuilder/FigureOfMerit/ResolutionGapProjMerit.h