#!/usr/bin/env python
# coding: utf-8

def build(ctx):

    lc_inc_dir = ctx.root.find_dir(ctx.top_dir).find_dir('latcommon/include')
    inc_dir = ctx.root.find_dir(ctx.top_dir).find_dir('include')

    ctx(features='cxx cxxprogram',
            source=ctx.path.ant_glob('*.cc'),
            includes=[inc_dir, lc_inc_dir],
            lib=ctx.env.LIB_FFTW + ctx.env.LIB_PROGRAM_OPTIONS + ctx.env.LIB_CHRONO + ctx.env.LIB_RT,
            stlib=ctx.env.STLIB_FFTW + ctx.env.STLIB_PROGRAM_OPTIONS + ctx.env.STLIB_CHRONO,
            target='bin/latbuilder',
            use=['latbuilder', 'latcommon'],
            install_path='${BINDIR}')
