#!/usr/bin/env python
# coding: utf-8

def build(ctx):

    lc_inc_dir = ctx.root.find_dir(ctx.top_dir).find_dir('latticetester/include')
    inc_dir = ctx.root.find_dir(ctx.top_dir).find_dir('include')


    ctx(features='cxx cxxprogram',
            source=ctx.path.ant_glob('*.cc'),
            includes=[inc_dir, lc_inc_dir],
            lib=ctx.env.LIB_FFTW + ctx.env.LIB_PROGRAM_OPTIONS + ctx.env.LIB_FILESYSTEM + ctx.env.LIB_SYSTEM + ctx.env.LIB_NTL + ctx.env.LIB_GMP,
            stlib=ctx.env.STLIB_FFTW + ctx.env.STLIB_PROGRAM_OPTIONS + ctx.env.STLIB_FILESYSTEM + ctx.env.STLIB_SYSTEM + ctx.env.STLIB_NTL + ctx.env.STLIB_GMP,
            target='bin/latnetbuilder',
            use=['latnetbuilder', 'latticetester'],
            install_path='${BINDIR}')
