LatNet Builder Manual: LatticeTester::CoordinateSets::Subsets Class Reference
LatticeTester::CoordinateSets::Subsets Class Reference
This class implements a CoordinateSets that will build all the subsets of a Coordinates object that are of a cardinality in a certain range.
#include <CoordinateSets.h>
Classes
class const_iterator
An iterator class used internaly by the Subsets class.
Public Member Functions
Subsets (const Coordinates &coords, Coordinates::size_type minOrder, Coordinates::size_type maxOrder)
Constructs a set of all subsets of coords with minimum and maximum cardinality specified by minOrder and maxOrder.
const Coordinates & coords () const
Returns the coordinates, as passed to the constructor.
Coordinates::size_type minOrder () const
Returns minOrder, as passed to the constructor.
Coordinates::size_type maxOrder () const
Returns maxOrder, as passed to the constructor.
const_iterator begin () const
Returns an iterator pointing to the first element of *this.
const_iterator end () const
Returns an iterator pointing past the last element of *this.
Detailed Description
This class implements a CoordinateSets that will build all the subsets of a Coordinates object that are of a cardinality in a certain range.
This is a less flexible class than FromRanges but, in the example Subsets.cc it has been slightly faster in our tests.
Remarks
it is somewhat hard to build an object of this class, maybe this could be done in a better way.
Constructor & Destructor Documentation
Subsets()
LatticeTester::CoordinateSets::Subsets::Subsets (const Coordinates & coords, Coordinates::size_type minOrder, Coordinates::size_type maxOrder)
Constructs a set of all subsets of coords with minimum and maximum cardinality specified by minOrder and maxOrder.
For example, to select all 1, 2, and 3-tuples over coordinates 2, 4, 6, one may use the declaration Subsets tousens(ens, 1, 3), where set ens is {2,4,6}; this gives the sets tousens = {{2}, {4}, {6}, {2, 4}, {2, 6}, {4, 6}, {2, 4, 6}}.
References coords(), maxOrder(), and minOrder().
Referenced by LatticeTester::CoordinateSets::Subsets::const_iterator::const_iterator(), LatticeTester::CoordinateSets::Subsets::const_iterator::const_iterator(), and LatticeTester::CoordinateSets::Subsets::const_iterator::operator++().
The documentation for this class was generated from the following file:
latticetester/include/latticetester/CoordinateSets.h