LatNet Builder Manual: NetBuilder::FigureOfMerit::FigureOfMeritEvaluator Class Reference
NetBuilder::FigureOfMerit::FigureOfMeritEvaluator Class Reference abstract
Evaluator abstract class to evaluate figure of merit for a net.
#include <FigureOfMerit.h>
Inherited by NetBuilder::FigureOfMerit::CBCFigureOfMeritEvaluator.
Public Types
typedef boost::signals2::signal< bool(const MeritValue &), LatBuilder::Functor::AllOf > OnProgress
typedef boost::signals2::signal< void(const AbstractDigitalNet &)> OnAbort
Public Member Functions
virtual ~FigureOfMeritEvaluator ()=default
Default virtual destructor.
FigureOfMeritEvaluator ()
Constructor.
Signals
OnProgress & onProgress () const
Progress signal.
OnAbort & onAbort () const
Abort signal.
virtual MeritValue operator() (const AbstractDigitalNet &net, int verbose=0)=0
Computes the figure of merit for the given net for all the dimensions (full computation).
virtual void reset ()=0
Resets the evaluator and prepare it to evaluate a new net.
Detailed Description
Evaluator abstract class to evaluate figure of merit for a net.
Member Function Documentation
onAbort()
OnAbort & NetBuilder::FigureOfMerit::FigureOfMeritEvaluator::onAbort () const inline
Abort signal.
Emitted if the computation of the figure of merit is aborted. The signal argument is the net for which the computation was aborted.
Referenced by NetBuilder::FigureOfMerit::CBCFigureOfMeritEvaluator::operator()(), and NetBuilder::FigureOfMerit::ProjectionDependentEvaluator< PROJDEP >::operator()().
onProgress()
OnProgress & NetBuilder::FigureOfMerit::FigureOfMeritEvaluator::onProgress () const inline
Progress signal.
Emitted after a contribution to the figure of merit is processed. The signal argument is the cumulative value of the figure of merit. If any of the signal slots returns false, the computation of the figure of merit will be aborted.
Referenced by NetBuilder::FigureOfMerit::CBCFigureOfMeritEvaluator::operator()(), and NetBuilder::FigureOfMerit::ProjectionDependentEvaluator< PROJDEP >::operator()().
operator()()
virtual MeritValue NetBuilder::FigureOfMerit::FigureOfMeritEvaluator::operator() (const AbstractDigitalNet & net, int verbose = 0) pure virtual
Computes the figure of merit for the given net for all the dimensions (full computation).
Parameters
net Net to evaluate.
verbose Verbosity level.
Implemented in NetBuilder::FigureOfMerit::CBCFigureOfMeritEvaluator.
reset()
virtual void NetBuilder::FigureOfMerit::FigureOfMeritEvaluator::reset () pure virtual
Resets the evaluator and prepare it to evaluate a new net.
Implemented in NetBuilder::FigureOfMerit::ProjectionDependentEvaluator< PROJDEP >, NetBuilder::FigureOfMerit::ProjectionDependentEvaluator< TValueProjMerit< EmbeddingType::MULTILEVEL, GaussMethod > >, NetBuilder::FigureOfMerit::ProjectionDependentEvaluator< TValueProjMerit< EmbeddingType::MULTILEVEL, SchmidMethod > >, NetBuilder::FigureOfMerit::ProjectionDependentEvaluator< TValueProjMerit< EmbeddingType::UNILEVEL, GaussMethod > >, NetBuilder::FigureOfMerit::ProjectionDependentEvaluator< TValueProjMerit< EmbeddingType::UNILEVEL, SchmidMethod > >, NetBuilder::FigureOfMerit::ProjectionDependentEvaluator< TValueTransformedProjMerit< EmbeddingType::MULTILEVEL, GaussMethod > >, NetBuilder::FigureOfMerit::ProjectionDependentEvaluator< TValueTransformedProjMerit< EmbeddingType::MULTILEVEL, SchmidMethod > >, NetBuilder::FigureOfMerit::ProjectionDependentEvaluator< TValueTransformedProjMerit< EmbeddingType::UNILEVEL, GaussMethod > >, and NetBuilder::FigureOfMerit::ProjectionDependentEvaluator< TValueTransformedProjMerit< EmbeddingType::UNILEVEL, SchmidMethod > >.
Referenced by NetBuilder::FigureOfMerit::CBCFigureOfMeritEvaluator::operator()().
The documentation for this class was generated from the following file:
include/netbuilder/FigureOfMerit/FigureOfMerit.h