#!/usr/bin/env python
# coding: utf-8

def build(ctx):
    src_dir = ctx.path.find_dir('src')
    inc_dir = ctx.path.find_dir('include')

    ctx(features='cxx cxxstlib',
            source=src_dir.ant_glob('[A-Z]*.cc'),
            includes=[inc_dir],
            target='latcommon',
            install_path='${LIBDIR}')

    ctx.install_files('${INCLUDEDIR}/latcommon', inc_dir.ant_glob('latcommon/*.h'))
