#!/usr/bin/env python
# coding: utf-8

def build(ctx):

    lc_inc_dir = ctx.root.find_dir(ctx.top_dir).find_dir('latcommon/include')
    lb_inc_dir = ctx.root.find_dir(ctx.top_dir).find_dir('latbuilder/include')

    for src in ctx.path.ant_glob('*.cc'):

        ctx(features='cxx cxxprogram test',
                source=src,
                includes=[lb_inc_dir, lc_inc_dir],
                lib=ctx.env.LIB_FFTW + ctx.env.LIB_PROGRAM_OPTIONS + ctx.env.LIB_CHRONO + ctx.env.LIB_RT,
                stlib=ctx.env.STLIB_FFTW + ctx.env.STLIB_PROGRAM_OPTIONS + ctx.env.STLIB_CHRONO,
                target=src.name[:-3],
                use=['latbuilder', 'latcommon'],
                install_path=None)

    ctx.install_files('${DOCDIR}/examples/tutorial', ctx.path.ant_glob('*.cc'))

    from waflib.Tools import waf_unit_test
    ctx.add_post_fun(waf_unit_test.summary)
