LatNet Builder Manual: NetBuilder::FigureOfMerit::TValueProjMerit< EmbeddingType::UNILEVEL, METHOD > Class Template Reference
NetBuilder::FigureOfMerit::TValueProjMerit< EmbeddingType::UNILEVEL, METHOD > Class Template Reference
Template specialization of the projection-dependent merit defined by the t-value of the projection in the case of unilevel nets.
#include <TValueProjMerit.h>
Inherited by NetBuilder::FigureOfMerit::TValueTransformedProjMerit< EmbeddingType::UNILEVEL, METHOD >.
Public Types
typedef std::unique_ptr< LevelCombiner::LevelCombiner > pCombiner
typedef unsigned int Merit
Type of the merit value.
typedef unsigned int SubProjCombination
Type of the subprojection combination of merit.
Public Member Functions
TValueProjMerit (unsigned int maxCardinal, pCombiner combiner=std::make_unique< LevelCombiner::LevelCombiner >())
Constructs a projection-dependent merit based on the t-value of projections.
unsigned int maxCardinal () const
Returns the maximum order of the subprojections to take into account.
virtual std::string format () const
Output information about the figure of merit.
Real operator() (const AbstractDigitalNet &net, const LatticeTester::Coordinates &projection, SubProjCombination maxMeritsSubProj) const
Computes the projection-dependent merit of the net net for the given projection.
virtual Real combine (Merit merit, const AbstractDigitalNet &net, const LatticeTester::Coordinates &projection)
Static Public Member Functions
static void update (Merit merit, SubProjCombination &subProjCombination)
Updates the combination of merit subProjCombination using merit.
static void setToZero (SubProjCombination &subProjCombination)
Initializes the combination of merit subProjCombination.
static unsigned int numLevels (const AbstractDigitalNet &net)
Determines the number of levels from a net.
static void resize (SubProjCombination &subProjCombination, unsigned int numLevels=1)
Resize the combination of merit subProjCombination to match the number of levels numLevels.
static unsigned int size (const SubProjCombination &subProjCombination)
Returns the size of the combination of merit subProjCombination.
Protected Attributes
unsigned int m_maxCardinal
Detailed Description
template<typename METHOD>
class NetBuilder::FigureOfMerit::TValueProjMerit< EmbeddingType::UNILEVEL, METHOD >
Template specialization of the projection-dependent merit defined by the t-value of the projection in the case of unilevel nets.
See also
NetBuilder::TValueProjMerit.
Constructor & Destructor Documentation
TValueProjMerit()
template<typename METHOD> NetBuilder::FigureOfMerit::TValueProjMerit< EmbeddingType::UNILEVEL, METHOD >::TValueProjMerit (unsigned int maxCardinal, pCombiner combiner = std::make_unique<LevelCombiner::LevelCombiner>()) inline
Constructs a projection-dependent merit based on the t-value of projections.
Parameters
maxCardinal Maximum order of the subprojections.
combiner Not used. For sake of uniformity.
References maxCardinal().
Referenced by NetBuilder::FigureOfMerit::TValueTransformedProjMerit< EmbeddingType::UNILEVEL, METHOD >::TValueTransformedProjMerit().
Member Function Documentation
format()
template<typename METHOD> virtual std::string NetBuilder::FigureOfMerit::TValueProjMerit< EmbeddingType::UNILEVEL, METHOD >::format () const inline virtual
Output information about the figure of merit.
Reimplemented in NetBuilder::FigureOfMerit::TValueTransformedProjMerit< EmbeddingType::UNILEVEL, METHOD >.
operator()()
template<typename METHOD> Real NetBuilder::FigureOfMerit::TValueProjMerit< EmbeddingType::UNILEVEL, METHOD >::operator() (const AbstractDigitalNet & net, const LatticeTester::Coordinates & projection, SubProjCombination maxMeritsSubProj) const inline
Computes the projection-dependent merit of the net net for the given projection.
Parameters
net Digital net to evaluate.
projection Projection to use.
maxMeritsSubProj Maximum of the t-value of the subprojections.
References NetBuilder::AbstractDigitalNet::generatingMatrix().
resize()
template<typename METHOD> void NetBuilder::FigureOfMerit::TValueProjMerit< EmbeddingType::UNILEVEL, METHOD >::resize (SubProjCombination & subProjCombination, unsigned int numLevels = 1) inline static
Resize the combination of merit subProjCombination to match the number of levels numLevels.
Parameters
subProjCombination Combination of merit to resize.
numLevels Number of levels.
References numLevels().
setToZero()
template<typename METHOD> void NetBuilder::FigureOfMerit::TValueProjMerit< EmbeddingType::UNILEVEL, METHOD >::setToZero (SubProjCombination & subProjCombination) inline static
Initializes the combination of merit subProjCombination.
Parameters
subProjCombination Combination of merit to initialized.
update()
template<typename METHOD> void NetBuilder::FigureOfMerit::TValueProjMerit< EmbeddingType::UNILEVEL, METHOD >::update (Merit merit, SubProjCombination & subProjCombination) inline static
Updates the combination of merit subProjCombination using merit.
Parameters
merit Merit used to update.
subProjCombination Combination of merit to update.
The documentation for this class was generated from the following file:
include/netbuilder/FigureOfMerit/TValueProjMerit.h