LatNet Builder Manual: NetBuilder::Task::ExhaustiveSearch< NC, ET, OBSERVER > Class Template Reference
NetBuilder::Task::ExhaustiveSearch< NC, ET, OBSERVER > Class Template Reference
Class for exhaustive search tasks.
#include <ExhaustiveSearch.h>
Inherits NetBuilder::Task::Search< NC, ET, MinimumObserver >.
Public Member Functions
ExhaustiveSearch (Dimension dimension, typename NetConstructionTraits< NC >::SizeParameter sizeParameter, std::unique_ptr< FigureOfMerit::FigureOfMerit > figure, int verbose=0, bool earlyAbortion=false)
Constructor.
ExhaustiveSearch (ExhaustiveSearch &&)=default
Default move constructor.
virtual std::string format () const override
Returns information about the task.
virtual void execute () override
Executes the search task.
virtual const FigureOfMerit::FigureOfMerit & figureOfMerit () const override
Returns a const qualified reference to the figure of merit.
Public Member Functions inherited from NetBuilder::Task::Search< NC, ET, MinimumObserver >
virtual ~Search ()=default
Virtual default destructor.
virtual void reset () override
Resets the search.
Search (Dimension dimension, typename NetConstructionTraits< NC >::SizeParameter sizeParameter, int verbose=0, bool earlyAbortion=false)
Constructor.
Dimension dimension () const
Returns the dimension of the searched net.
unsigned int nRows () const
Returns the number of rows of the searched generating matrices.
unsigned int nCols () const
Returns the number of columns of the searched generating matrices.
const DigitalNet< NC > & bestNet () const
Returns the best net found by the search.
Real bestMeritValue () const
Returns the best merit found by the search.
bool hasFoundNet () const
virtual std::string outputNet (OutputStyle outputStyle, unsigned int interlacingFactor) const override
Returns the best net found by the search task.
virtual Real outputMeritValue () const override
Returns the best merit value found by the search task.
Observer & observer ()
Returns a reference to the minimum-element observer.
OnNetSelected & onNetSelected ()
Net-selected signal.
OnFailedSearch & onFailedSearch ()
Failed search signal.
const NetConstructionTraits< NC >::SizeParameter & sizeParameter () const
Returns a const qualified reference to the size parameter of the search.
Additional Inherited Members
Public Types inherited from NetBuilder::Task::Search< NC, ET, MinimumObserver >
typedef MinimumObserver< NC > Observer
Observer of the search.
typedef boost::signals2::signal< void(const Search< NC, ET, MinimumObserver > &)> OnNetSelected
Signal emitted when a net has been selected.
typedef boost::signals2::signal< void(const Search< NC, ET, MinimumObserver > &)> OnFailedSearch
Signal emitted when the search has failed.
Protected Member Functions inherited from NetBuilder::Task::Search< NC, ET, MinimumObserver >
void selectBestNet (const DigitalNet< NC > &net, Real merit)
Selects a new best net and emits an OnNetSelected signal.
Protected Attributes inherited from NetBuilder::Task::Search< NC, ET, MinimumObserver >
std::unique_ptr< OnNetSelected > m_onNetSelected
std::unique_ptr< OnFailedSearch > m_onFailedSearch
Dimension m_dimension
NetConstructionTraits< NC >::SizeParameter m_sizeParameter
unsigned int m_nRows
unsigned int m_nCols
DigitalNet< NC > m_bestNet
Real m_bestMerit
std::unique_ptr< Observer > m_observer
int m_verbose
bool m_earlyAbortion
Detailed Description
template<NetConstruction NC, EmbeddingType ET, template< NetConstruction > class OBSERVER = MinimumObserver>
class NetBuilder::Task::ExhaustiveSearch< NC, ET, OBSERVER >
Class for exhaustive search tasks.
Constructor & Destructor Documentation
ExhaustiveSearch() [1/2]
template<NetConstruction NC, EmbeddingType ET, template< NetConstruction > class OBSERVER = MinimumObserver> NetBuilder::Task::ExhaustiveSearch< NC, ET, OBSERVER >::ExhaustiveSearch (Dimension dimension, typename NetConstructionTraits< NC >::SizeParameter sizeParameter, std::unique_ptr< FigureOfMerit::FigureOfMerit > figure, int verbose = 0, bool earlyAbortion = false) inline
Constructor.
Parameters
dimension Dimension of the searched net.
sizeParameter Size parameter of the searched net.
figure Figure of merit used to compare nets.
verbose Verbosity level.
earlyAbortion Early-abortion switch. If true, the computations will be stopped if the net is worse than the best one so far.
References NetBuilder::Task::Search< NC, ET, MinimumObserver >::dimension(), NetBuilder::Task::Search< NC, ET, MinimumObserver >::Search(), and NetBuilder::Task::Search< NC, ET, MinimumObserver >::sizeParameter().
Referenced by ExhaustiveSearch().
ExhaustiveSearch() [2/2]
template<NetConstruction NC, EmbeddingType ET, template< NetConstruction > class OBSERVER = MinimumObserver> NetBuilder::Task::ExhaustiveSearch< NC, ET, OBSERVER >::ExhaustiveSearch (ExhaustiveSearch< NC, ET, OBSERVER > &&) default
Default move constructor.
Deletes the implicit copy constructor.
References ExhaustiveSearch().
Member Function Documentation
execute()
template<NetConstruction NC, EmbeddingType ET, template< NetConstruction > class OBSERVER = MinimumObserver> virtual void NetBuilder::Task::ExhaustiveSearch< NC, ET, OBSERVER >::execute () inline override virtual
Executes the search task.
The best net and merit value are set in the process.
Implements NetBuilder::Task::Search< NC, ET, MinimumObserver >.
References NetBuilder::Task::Search< NC, ET, MinimumObserver >::dimension(), NetBuilder::Task::Search< NC, ET, MinimumObserver >::observer(), NetBuilder::Task::Search< NC, ET, MinimumObserver >::onFailedSearch(), NetBuilder::Task::Search< NC, ET, MinimumObserver >::Search(), and NetBuilder::Task::Search< NC, ET, MinimumObserver >::selectBestNet().
figureOfMerit()
template<NetConstruction NC, EmbeddingType ET, template< NetConstruction > class OBSERVER = MinimumObserver> virtual const FigureOfMerit::FigureOfMerit & NetBuilder::Task::ExhaustiveSearch< NC, ET, OBSERVER >::figureOfMerit () const inline override virtual
Returns a const qualified reference to the figure of merit.
Implements NetBuilder::Task::Search< NC, ET, MinimumObserver >.
format()
template<NetConstruction NC, EmbeddingType ET, template< NetConstruction > class OBSERVER = MinimumObserver> virtual std::string NetBuilder::Task::ExhaustiveSearch< NC, ET, OBSERVER >::format () const inline override virtual
Returns information about the task.
Reimplemented from NetBuilder::Task::Search< NC, ET, MinimumObserver >.
The documentation for this class was generated from the following file:
include/netbuilder/Task/ExhaustiveSearch.h