LatNet Builder Manual: NetBuilder::FigureOfMerit::CBCFigureOfMeritEvaluator Class Reference
NetBuilder::FigureOfMerit::CBCFigureOfMeritEvaluator Class Reference abstract
Evaluator abstract class to evaluate figure of merit for a net in a CBC way.
#include <FigureOfMerit.h>
Inherits NetBuilder::FigureOfMerit::FigureOfMeritEvaluator.
Inherited by NetBuilder::FigureOfMerit::ProjectionDependentEvaluator< TValueProjMerit< EmbeddingType::MULTILEVEL, GaussMethod > >, NetBuilder::FigureOfMerit::ProjectionDependentEvaluator< TValueProjMerit< EmbeddingType::MULTILEVEL, SchmidMethod > >, NetBuilder::FigureOfMerit::ProjectionDependentEvaluator< TValueProjMerit< EmbeddingType::UNILEVEL, GaussMethod > >, NetBuilder::FigureOfMerit::ProjectionDependentEvaluator< TValueProjMerit< EmbeddingType::UNILEVEL, SchmidMethod > >, NetBuilder::FigureOfMerit::ProjectionDependentEvaluator< TValueTransformedProjMerit< EmbeddingType::MULTILEVEL, GaussMethod > >, NetBuilder::FigureOfMerit::ProjectionDependentEvaluator< TValueTransformedProjMerit< EmbeddingType::MULTILEVEL, SchmidMethod > >, NetBuilder::FigureOfMerit::ProjectionDependentEvaluator< TValueTransformedProjMerit< EmbeddingType::UNILEVEL, GaussMethod > >, NetBuilder::FigureOfMerit::ProjectionDependentEvaluator< TValueTransformedProjMerit< EmbeddingType::UNILEVEL, SchmidMethod > >, and NetBuilder::FigureOfMerit::ProjectionDependentEvaluator< PROJDEP >.
Public Member Functions
virtual MeritValue operator() (const AbstractDigitalNet &net, int verbose=0) override
inheritDoc}
virtual MeritValue operator() (const AbstractDigitalNet &net, Dimension dimension, MeritValue initialValue, int verbose=0)=0
Computes the figure of merit for the given net for the given dimension (partial computation), starting from the initial value initialValue.
virtual void prepareForNextDimension ()=0
Tells the evaluator that no more net will be evaluate for the current dimension, store information about the best net for the dimension which is over and prepare data structures for the next dimension.
virtual void lastNetWasBest ()=0
Tells the evaluator that the last net was the best so far and store the relevant information.
Public Member Functions inherited from NetBuilder::FigureOfMerit::FigureOfMeritEvaluator
virtual ~FigureOfMeritEvaluator ()=default
Default virtual destructor.
FigureOfMeritEvaluator ()
Constructor.
OnProgress & onProgress () const
Progress signal.
OnAbort & onAbort () const
Abort signal.
virtual void reset ()=0
Resets the evaluator and prepare it to evaluate a new net.
Additional Inherited Members
Public Types inherited from NetBuilder::FigureOfMerit::FigureOfMeritEvaluator
typedef boost::signals2::signal< bool(const MeritValue &), LatBuilder::Functor::AllOf > OnProgress
typedef boost::signals2::signal< void(const AbstractDigitalNet &)> OnAbort
Detailed Description
Evaluator abstract class to evaluate figure of merit for a net in a CBC way.
Member Function Documentation
lastNetWasBest()
virtual void NetBuilder::FigureOfMerit::CBCFigureOfMeritEvaluator::lastNetWasBest () pure virtual
Tells the evaluator that the last net was the best so far and store the relevant information.
Implemented in NetBuilder::FigureOfMerit::ProjectionDependentEvaluator< PROJDEP >, NetBuilder::FigureOfMerit::ProjectionDependentEvaluator< TValueProjMerit< EmbeddingType::MULTILEVEL, GaussMethod > >, NetBuilder::FigureOfMerit::ProjectionDependentEvaluator< TValueProjMerit< EmbeddingType::MULTILEVEL, SchmidMethod > >, NetBuilder::FigureOfMerit::ProjectionDependentEvaluator< TValueProjMerit< EmbeddingType::UNILEVEL, GaussMethod > >, NetBuilder::FigureOfMerit::ProjectionDependentEvaluator< TValueProjMerit< EmbeddingType::UNILEVEL, SchmidMethod > >, NetBuilder::FigureOfMerit::ProjectionDependentEvaluator< TValueTransformedProjMerit< EmbeddingType::MULTILEVEL, GaussMethod > >, NetBuilder::FigureOfMerit::ProjectionDependentEvaluator< TValueTransformedProjMerit< EmbeddingType::MULTILEVEL, SchmidMethod > >, NetBuilder::FigureOfMerit::ProjectionDependentEvaluator< TValueTransformedProjMerit< EmbeddingType::UNILEVEL, GaussMethod > >, and NetBuilder::FigureOfMerit::ProjectionDependentEvaluator< TValueTransformedProjMerit< EmbeddingType::UNILEVEL, SchmidMethod > >.
Referenced by operator()().
operator()() [1/2]
virtual MeritValue NetBuilder::FigureOfMerit::CBCFigureOfMeritEvaluator::operator() (const AbstractDigitalNet & net, Dimension dimension, MeritValue initialValue, int verbose = 0) pure virtual
Computes the figure of merit for the given net for the given dimension (partial computation), starting from the initial value initialValue.
Intended to be specialized based on template parameter ET.
Parameters
net Net to evaluate.
dimension Dimension to compute.
initialValue Initial value of the merit.
verbose Verbosity level.
Implemented in NetBuilder::FigureOfMerit::ProjectionDependentEvaluator< PROJDEP >, NetBuilder::FigureOfMerit::ProjectionDependentEvaluator< TValueProjMerit< EmbeddingType::MULTILEVEL, GaussMethod > >, NetBuilder::FigureOfMerit::ProjectionDependentEvaluator< TValueProjMerit< EmbeddingType::MULTILEVEL, SchmidMethod > >, NetBuilder::FigureOfMerit::ProjectionDependentEvaluator< TValueProjMerit< EmbeddingType::UNILEVEL, GaussMethod > >, NetBuilder::FigureOfMerit::ProjectionDependentEvaluator< TValueProjMerit< EmbeddingType::UNILEVEL, SchmidMethod > >, NetBuilder::FigureOfMerit::ProjectionDependentEvaluator< TValueTransformedProjMerit< EmbeddingType::MULTILEVEL, GaussMethod > >, NetBuilder::FigureOfMerit::ProjectionDependentEvaluator< TValueTransformedProjMerit< EmbeddingType::MULTILEVEL, SchmidMethod > >, NetBuilder::FigureOfMerit::ProjectionDependentEvaluator< TValueTransformedProjMerit< EmbeddingType::UNILEVEL, GaussMethod > >, and NetBuilder::FigureOfMerit::ProjectionDependentEvaluator< TValueTransformedProjMerit< EmbeddingType::UNILEVEL, SchmidMethod > >.
operator()() [2/2]
virtual MeritValue NetBuilder::FigureOfMerit::CBCFigureOfMeritEvaluator::operator() (const AbstractDigitalNet & net, int verbose = 0) inline override virtual
inheritDoc}
Implements NetBuilder::FigureOfMerit::FigureOfMeritEvaluator.
References NetBuilder::AbstractDigitalNet::dimension(), lastNetWasBest(), NetBuilder::FigureOfMerit::FigureOfMeritEvaluator::onAbort(), NetBuilder::FigureOfMerit::FigureOfMeritEvaluator::onProgress(), operator()(), prepareForNextDimension(), and NetBuilder::FigureOfMerit::FigureOfMeritEvaluator::reset().
Referenced by operator()().
prepareForNextDimension()
virtual void NetBuilder::FigureOfMerit::CBCFigureOfMeritEvaluator::prepareForNextDimension () pure virtual
Tells the evaluator that no more net will be evaluate for the current dimension, store information about the best net for the dimension which is over and prepare data structures for the next dimension.
Implemented in NetBuilder::FigureOfMerit::ProjectionDependentEvaluator< PROJDEP >, NetBuilder::FigureOfMerit::ProjectionDependentEvaluator< TValueProjMerit< EmbeddingType::MULTILEVEL, GaussMethod > >, NetBuilder::FigureOfMerit::ProjectionDependentEvaluator< TValueProjMerit< EmbeddingType::MULTILEVEL, SchmidMethod > >, NetBuilder::FigureOfMerit::ProjectionDependentEvaluator< TValueProjMerit< EmbeddingType::UNILEVEL, GaussMethod > >, NetBuilder::FigureOfMerit::ProjectionDependentEvaluator< TValueProjMerit< EmbeddingType::UNILEVEL, SchmidMethod > >, NetBuilder::FigureOfMerit::ProjectionDependentEvaluator< TValueTransformedProjMerit< EmbeddingType::MULTILEVEL, GaussMethod > >, NetBuilder::FigureOfMerit::ProjectionDependentEvaluator< TValueTransformedProjMerit< EmbeddingType::MULTILEVEL, SchmidMethod > >, NetBuilder::FigureOfMerit::ProjectionDependentEvaluator< TValueTransformedProjMerit< EmbeddingType::UNILEVEL, GaussMethod > >, and NetBuilder::FigureOfMerit::ProjectionDependentEvaluator< TValueTransformedProjMerit< EmbeddingType::UNILEVEL, SchmidMethod > >.
Referenced by operator()().
The documentation for this class was generated from the following file:
include/netbuilder/FigureOfMerit/FigureOfMerit.h