LatNet Builder Manual: NetBuilder::DigitalNet< NC > Class Template Reference
NetBuilder::DigitalNet< NC > Class Template Reference
Derived class of AbstractDigitalNet designed to implement specific construction methods.
#include <DigitalNet.h>
Inherits NetBuilder::AbstractDigitalNet.
Public Types
typedef NetConstructionTraits< NC > ConstructionMethod
typedef ConstructionMethod::GenValue GenValue
Type of the generating values of the method. The generating value is the parameter needed to construct a.
typedef ConstructionMethod::SizeParameter SizeParameter
Type of the size parameter of the method. The size parameters are the parameters needed to construct.
Public Member Functions
DigitalNet (Dimension dimension, SizeParameter sizeParameter, std::vector< GenValue > genValues)
Construction of a net from its size parameter and generating values.
DigitalNet (Dimension dimension=0, SizeParameter sizeParameter=SizeParameter())
Dummy constructor for placeholder nets.
~DigitalNet ()=default
Default destructor.
std::unique_ptr< DigitalNet< NC > > appendNewCoordinate (const GenValue &newGenValue) const
Adds a new coordinate at the end of a digital net using the generating value newGenValue.
virtual std::string format (OutputStyle outputStyle=OutputStyle::TERMINAL, unsigned int interlacingFactor=1) const
Formats the net for output.
Parameters
outputFormat Format of output.
interlacingFactor Interlacing factor of the net.
outputStyle Specific Format of output Machine format.
virtual bool isSequenceViewable () const
Returns a bool indicating whether the net can be viewed as a digital sequence.
SizeParameter sizeParameter () const
Public Member Functions inherited from NetBuilder::AbstractDigitalNet
AbstractDigitalNet (Dimension dimension=0, unsigned int nRows=0, unsigned int nCols=0)
Default constructor.
virtual ~AbstractDigitalNet ()=default
Default destructor.
unsigned int numColumns () const
Returns the number of columns of the generating matrices.
unsigned int numRows () const
Returns the number of rows of the generating matrices.
uInteger numPoints () const
Returns the number of points of the net.
uInteger size () const
Returns the number of points of the net.
Dimension dimension () const
Returns the dimension (number of coordinates) of the net.
const GeneratingMatrix & generatingMatrix (Dimension coord) const
Returns the generating matrix corresponding to coordinate coord.
Additional Inherited Members
Protected Member Functions inherited from NetBuilder::AbstractDigitalNet
AbstractDigitalNet (Dimension dimension, unsigned int nRows, unsigned int nCols, std::vector< std::shared_ptr< GeneratingMatrix > > genMatrices)
Most general constructor.
Protected Attributes inherited from NetBuilder::AbstractDigitalNet
Dimension m_dimension
unsigned int m_nRows
unsigned int m_nCols
std::vector< std::shared_ptr< GeneratingMatrix > > m_generatingMatrices
Detailed Description
template<NetConstruction NC>
class NetBuilder::DigitalNet< NC >
Derived class of AbstractDigitalNet designed to implement specific construction methods.
The available construction methods are described by the NetConstruction enumeration which is a non-type template parameter of the DigitalNet class. Construction methods are based on two parameters: a size parameter which is shared by all coordinates and a sequence of generating values, each of them being associated to one coordinate. It is templated by a NetConstructionTraits, which describes the construction method.
See also
NetBuilder::NetConstructionTraits
Examples
tutorial/NetQuantiles.cc.
Constructor & Destructor Documentation
DigitalNet() [1/2]
template<NetConstruction NC> NetBuilder::DigitalNet< NC >::DigitalNet (Dimension dimension, SizeParameter sizeParameter, std::vector< GenValue > genValues) inline
Construction of a net from its size parameter and generating values.
This operation computes and stores the generating matrices of the net.
Parameters
dimension Dimension of the net.
sizeParameter Size parameter of the net.
genValues Sequence of generating values to create the net.
References NetBuilder::AbstractDigitalNet::AbstractDigitalNet(), and NetBuilder::AbstractDigitalNet::dimension().
Referenced by appendNewCoordinate().
DigitalNet() [2/2]
template<NetConstruction NC> NetBuilder::DigitalNet< NC >::DigitalNet (Dimension dimension = 0, SizeParameter sizeParameter = SizeParameter()) inline
Dummy constructor for placeholder nets.
Parameters
dimension Dimension of the net.
sizeParameter Size parameter of the net.
References NetBuilder::AbstractDigitalNet::AbstractDigitalNet(), and NetBuilder::AbstractDigitalNet::dimension().
Member Function Documentation
appendNewCoordinate()
template<NetConstruction NC> std::unique_ptr< DigitalNet< NC > > NetBuilder::DigitalNet< NC >::appendNewCoordinate (const GenValue & newGenValue) const inline
Adds a new coordinate at the end of a digital net using the generating value newGenValue.
Note that the resources (generating matrices, generatins values and computation data) for the lower dimensions are not copied. The net on which this method is called and the new net share these resources.
Parameters
newGenValue Generating value used to extend the net.
Returns
A std::unique_ptr to the instantiated net.
References DigitalNet().
format()
template<NetConstruction NC> virtual std::string NetBuilder::DigitalNet< NC >::format (OutputStyle outputStyle = OutputStyle::TERMINAL, unsigned int interlacingFactor = 1) const inline virtual
Formats the net for output.
Parameters
outputFormat Format of output.
interlacingFactor Interlacing factor of the net.
outputStyle Specific Format of output Machine format.
Implements NetBuilder::AbstractDigitalNet.
References NetBuilder::AbstractDigitalNet::dimension(), NetBuilder::AbstractDigitalNet::numColumns(), NetBuilder::AbstractDigitalNet::numPoints(), and NetBuilder::AbstractDigitalNet::numRows().
isSequenceViewable()
template<NetConstruction NC> virtual bool NetBuilder::DigitalNet< NC >::isSequenceViewable () const inline virtual
Returns a bool indicating whether the net can be viewed as a digital sequence.
Implements NetBuilder::AbstractDigitalNet.
The documentation for this class was generated from the following file:
include/netbuilder/DigitalNet.h