LatNet Builder Manual: LatBuilder::MeritSeq::CoordUniformCBC< LR, ET, COMPRESS, PLO, KERNEL, PROD > Class Template Reference
LatBuilder::MeritSeq::CoordUniformCBC< LR, ET, COMPRESS, PLO, KERNEL, PROD > Class Template Reference
Sequence of lattice merit for weighted coordinate-uniform figures of merit.
#include <CoordUniformCBC.h>
Classes
class Seq
Output sequence from the coordinate-uniform CBC algorithm.
Public Types
typedef PROD< LR, ET, COMPRESS, PLO > CoordUniformInnerProd
typedef Storage< LR, ET, COMPRESS, PLO >::MeritValue MeritValue
typedef LatBuilder::LatDef< LR, ET > LatDef
typedef CoordUniformFigureOfMerit< KERNEL > FigureOfMerit
typedef CoordUniformInnerProd::StateList StateList
typedef MeritValue value_type
typedef LatticeTraits< LR >::GenValue GenValue
Public Member Functions
CoordUniformCBC (Storage< LR, ET, COMPRESS, PLO > storage, const FigureOfMerit &figure)
Constructor.
void reset ()
Resets the state of the CBC algorithm to dimension 0.
const Storage< LR, ET, COMPRESS, PLO > & storage () const
Returns the storage configuration instance.
const FigureOfMerit & figureOfMerit () const
Returns the coordinate-uniform figure of merit.
const CoordUniformInnerProd & innerProd () const
Returns the inner product instance.
const StateList & states () const
Returns the states.
RealVector weightedState () const
Returns the total weighted state.
const LatDef & baseLat () const
Returns the base lattice.
const MeritValue & baseMerit () const
Returns the base merit value.
template<typename GENSEQ>
Seq< GENSEQ > meritSeq (const GENSEQ &genSeq) const
Creates a new sequence of merit values by appending the values in genSeq to the generating vector of the base lattice.
template<typename IT>
void select (const IT &it)
Selects the element pointed to by the iterator.
Detailed Description
template<LatticeType LR, EmbeddingType ET, Compress COMPRESS, PerLevelOrder PLO, class KERNEL, template< LatticeType, EmbeddingType, Compress, PerLevelOrder > class PROD = CoordUniformInnerProd>
class LatBuilder::MeritSeq::CoordUniformCBC< LR, ET, COMPRESS, PLO, KERNEL, PROD >
Sequence of lattice merit for weighted coordinate-uniform figures of merit.
A weighted coordinate-uniform figure of merit is of the form:
\[ \mathcal D^2 = \sum_{\emptyset \neq \mathfrak u \subseteq \{1, \dots, s\}} \gamma_{\mathfrak u} \frac1n \sum_{i=0}^{n-1} \prod_{j \in \mathfrak u} \omega(x_{i,j}), \]
for some function \(\omega: [0,1) \to [0,\infty)\).
Template Parameters
ET Type of lattice.
COMPRESS Type of compression.
KERNEL Kernel of the coordinate-uniform figure of merit; should derive from Kernel::Base.
PROD Type of inner product; either CoordUniformInnerProd or CoordUniformInnerProdFast.
Constructor & Destructor Documentation
CoordUniformCBC()
template<LatticeType LR, EmbeddingType ET, Compress COMPRESS, PerLevelOrder PLO, class KERNEL, template< LatticeType, EmbeddingType, Compress, PerLevelOrder > class PROD = CoordUniformInnerProd> LatBuilder::MeritSeq::CoordUniformCBC< LR, ET, COMPRESS, PLO, KERNEL, PROD >::CoordUniformCBC (Storage< LR, ET, COMPRESS, PLO > storage, const FigureOfMerit & figure) inline
Constructor.
Parameters
storage Storage configuration.
figure Coordinate-uniform figure of merit.
Referenced by LatBuilder::MeritSeq::CoordUniformCBC< LR, ET, COMPRESS, PLO, KERNEL, PROD >::Seq< GENSEQ >::cbc(), and LatBuilder::MeritSeq::CoordUniformCBC< LR, ET, COMPRESS, PLO, KERNEL, PROD >::Seq< GENSEQ >::Seq().
Member Function Documentation
baseLat()
template<LatticeType LR, EmbeddingType ET, Compress COMPRESS, PerLevelOrder PLO, class KERNEL, template< LatticeType, EmbeddingType, Compress, PerLevelOrder > class PROD = CoordUniformInnerProd> const LatDef & LatBuilder::MeritSeq::CoordUniformCBC< LR, ET, COMPRESS, PLO, KERNEL, PROD >::baseLat () const inline
Returns the base lattice.
This sequence extends on the lattice base by increasing its dimension by one.
See also
baseMerit()
Referenced by LatBuilder::MeritSeq::CoordUniformCBC< LR, ET, COMPRESS, PLO, KERNEL, PROD >::Seq< GENSEQ >::Seq().
baseMerit()
template<LatticeType LR, EmbeddingType ET, Compress COMPRESS, PerLevelOrder PLO, class KERNEL, template< LatticeType, EmbeddingType, Compress, PerLevelOrder > class PROD = CoordUniformInnerProd> const MeritValue & LatBuilder::MeritSeq::CoordUniformCBC< LR, ET, COMPRESS, PLO, KERNEL, PROD >::baseMerit () const inline
Returns the base merit value.
The merit values contained in this sequence are based on the value returned by this function.
See also
baseLat()
meritSeq()
template<LatticeType LR, EmbeddingType ET, Compress COMPRESS, PerLevelOrder PLO, class KERNEL, template< LatticeType, EmbeddingType, Compress, PerLevelOrder > class PROD = CoordUniformInnerProd> template<typename GENSEQ> Seq< GENSEQ > LatBuilder::MeritSeq::CoordUniformCBC< LR, ET, COMPRESS, PLO, KERNEL, PROD >::meritSeq (const GENSEQ & genSeq) const inline
Creates a new sequence of merit values by appending the values in genSeq to the generating vector of the base lattice.
Parameters
genSeq Sequence of generator values.
select()
template<LatticeType LR, EmbeddingType ET, Compress COMPRESS, PerLevelOrder PLO, class KERNEL, template< LatticeType, EmbeddingType, Compress, PerLevelOrder > class PROD = CoordUniformInnerProd> template<typename IT> void LatBuilder::MeritSeq::CoordUniformCBC< LR, ET, COMPRESS, PLO, KERNEL, PROD >::select (const IT & it) inline
Selects the element pointed to by the iterator.
Returns true if and only if the sequence of generator sequences is not exhausted.
Parameters
it Iterator on the element of the sequence to be selected.
The documentation for this class was generated from the following file:
include/latbuilder/MeritSeq/CoordUniformCBC.h