LatNet Builder Manual: NTL::vector< T > Class Template Reference
NTL::vector< T > Class Template Reference
A subclass of the NTL::Vec<T> class.
#include <ntlwrap.h>
Inherits Vec< T >.
Public Types
typedef std::int64_t size_type
Public Member Functions
vector ()
Empty constructor.
vector (size_type size)
Allocation constructor.
vector (const Vec< T > &v)
Copy constructor.
~vector ()
Destructor.
void resize (size_type size)
Set the vector lenght to size.
void clear ()
Releases space and sets length to 0.
size_type size () const
Returns the current lenght of the vector.
size_type max_size () const
Returns the number of allocated and initialized elements in the vector.
void push_back (const T &element)
a copy from NTL::Vec<T>::append
T back ()
return the last element, this one is for STL compatibility
bool empty () const
Returns true if the vector has length 0 and false otherwise.
const T & operator() (size_type i) const
Change in the indexation reference for () operator to start from 0.
T & operator() (size_type i)
Detailed Description
template<typename T>
class NTL::vector< T >
A subclass of the NTL::Vec<T> class.
It extends its parent with a few methods and overloads a few others with more compatible defaults.
Constructor & Destructor Documentation
vector() [1/3]
template<typename T > NTL::vector< T >::vector () inline
Empty constructor.
Creates a vector of size 0.
vector() [2/3]
template<typename T > NTL::vector< T >::vector (size_type size) inline
Allocation constructor.
Allocates the space needed by a vector of size size.
Parameters
size The size of the vector
vector() [3/3]
template<typename T > NTL::vector< T >::vector (const Vec< T > & v) inline
Copy constructor.
Makes a copy of v.
Parameters
v Vector to be copied.
~vector()
template<typename T > NTL::vector< T >::~vector () inline
Destructor.
Frees memory of all T and destroys the vector.
Member Function Documentation
clear()
template<typename T > void NTL::vector< T >::clear () inline
Releases space and sets length to 0.
This uses NTL::Vec<T>::kill().
max_size()
template<typename T > size_type NTL::vector< T >::max_size () const inline
Returns the number of allocated and initialized elements in the vector.
It is possible for the vector length to differ from this one if the max length has been preemptively expanded or if the vector has been shrinked because NTL does not free components until explicitly asked. This uses NTL::Vec<T>::MaxLength().
operator()()
template<typename T > const T & NTL::vector< T >::operator() (size_type i) const inline
Change in the indexation reference for () operator to start from 0.
In NTL::Vec<T> the () operator starts from 1 which is not compatible with boost.
resize()
template<typename T > void NTL::vector< T >::resize (size_type size) inline
Set the vector lenght to size.
New objects are initialized using the default contructor for T This uses NTL::Vec<T>::SetLength(size)
Parameters
size The new size wanted
References NTL::vector< T >::size().
Referenced by LatticeTester::IntLattice< Int, BasInt, Dbl, RedDbl >::IntLattice(), LatticeTester::IntLatticeBasis< Int, BasInt, Dbl, RedDbl >::IntLatticeBasis(), LatticeTester::IntLatticeBasis< Int, BasInt, Dbl, RedDbl >::IntLatticeBasis(), and LatticeTester::IntLatticeBasis< Int, BasInt, Dbl, RedDbl >::IntLatticeBasis().
size()
template<typename T > size_type NTL::vector< T >::size () const inline
Returns the current lenght of the vector.
This uses NTL::Vec<T>::length().
Referenced by NTL::vector< T >::empty(), LatBuilder::GenSeq::GeneratingValues< LatticeType::POLYNOMIAL, COMPRESS, TRAV >::GeneratingValues(), and NTL::vector< T >::resize().
The documentation for this class was generated from the following file:
latticetester/include/latticetester/ntlwrap.h