LatNet Builder Manual: LatBuilder::Norm::NormAlphaBase< DERIVED > Class Template Reference
LatBuilder::Norm::NormAlphaBase< DERIVED > Class Template Reference
Base class for bounds on the \(\mathcal P_\alpha\) values.
#include <NormAlphaBase.h>
Public Member Functions
NormAlphaBase (unsigned int alpha, Real normType)
Constructor.
unsigned alpha () const
Real normType () const
Real minExp () const
Real maxExp () const
template<LatticeType LR, EmbeddingType L>
Real value (Real lambda, const SizeParam< LR, L > &sizeParam, Dimension dimension, Real norm=1.0) const
Returns the value of the bound.
template<LatticeType LR, EmbeddingType L>
Real operator() (const SizeParam< LR, L > &sizeParam, Dimension dimension, Real norm=1.0) const
Returns the smallest value of the bound for dimension dimension.
template<LatticeType LR, EmbeddingType L>
Real minimum (const SizeParam< LR, L > &sizeParam, Dimension dimension, Real norm) const
Returns the minimum value of the bound function.
Static Public Attributes
static const unsigned MINIMIZER_MAX_ITER = 1000u
Maximum number of iterations to be used with the minimizer.
static const int MINIMIZER_PREC_BITS = 18
Relative precision on the minimum value to be used with the minimizer.
Detailed Description
template<class DERIVED>
class LatBuilder::Norm::NormAlphaBase< DERIVED >
Base class for bounds on the \(\mathcal P_\alpha\) values.
Constructor & Destructor Documentation
NormAlphaBase()
template<class DERIVED > LatBuilder::Norm::NormAlphaBase< DERIVED >::NormAlphaBase (unsigned int alpha, Real normType) inline
Constructor.
Parameters
alpha Smoothness level \(\alpha\) of the class of functions.
normType Type of cross-projection norm used by the figure of merit.
Member Function Documentation
minimum()
template<class DERIVED > template<LatticeType LR, EmbeddingType L> Real LatBuilder::Norm::NormAlphaBase< DERIVED >::minimum (const SizeParam< LR, L > & sizeParam, Dimension dimension, Real norm) const inline
Returns the minimum value of the bound function.
Uses BrentMinimizer to minimize the bound function. The value of \(\lambda\) at which the minimum is reached is not returned.
References LatBuilder::Norm::NormAlphaBase< DERIVED >::MINIMIZER_MAX_ITER, LatBuilder::Norm::NormAlphaBase< DERIVED >::MINIMIZER_PREC_BITS, and LatBuilder::Norm::NormAlphaBase< DERIVED >::value().
Referenced by LatBuilder::Norm::NormAlphaBase< DERIVED >::operator()().
operator()()
template<class DERIVED > template<LatticeType LR, EmbeddingType L> Real LatBuilder::Norm::NormAlphaBase< DERIVED >::operator() (const SizeParam< LR, L > & sizeParam, Dimension dimension, Real norm = 1.0) const inline
Returns the smallest value of the bound for dimension dimension.
Parameters
sizeParam Size parameter for the lattices.
dimension Dimension.
norm Additional normalization \(c \).
References LatBuilder::Norm::NormAlphaBase< DERIVED >::minimum().
value()
template<class DERIVED > template<LatticeType LR, EmbeddingType L> Real LatBuilder::Norm::NormAlphaBase< DERIVED >::value (Real lambda, const SizeParam< LR, L > & sizeParam, Dimension dimension, Real norm = 1.0) const inline
Returns the value of the bound.
Parameters
lambda Value of \(\lambda = \).
sizeParam Size parameter for the lattices.
dimension Dimension.
norm Additional normalization \(c \).
Referenced by LatBuilder::Norm::NormAlphaBase< DERIVED >::minimum().
The documentation for this class was generated from the following file:
include/latbuilder/Norm/NormAlphaBase.h