LatNet Builder Manual: LatticeTester::CoordinateSets::Subsets::const_iterator Class Reference
LatticeTester::CoordinateSets::Subsets::const_iterator Class Reference
An iterator class used internaly by the Subsets class.
#include <CoordinateSets.h>
Inherits std::iterator< std::forward_iterator_tag, const Coordinates >.
Classes
struct end_tag
Public Member Functions
const_iterator (const Subsets &seq)
Constructor for an iterator at the begining of the list of sets that seq contains.
const_iterator (const Subsets &seq, end_tag)
Constructor for an iterator at the end of the list of sets that seq contains.
const_iterator (const const_iterator &other)
Copy constructor.
const_iterator ()
Default constructor.
const_iterator & operator= (const const_iterator &other)
Assignment operator that does the same as the copy constructor.
bool operator== (const const_iterator &other)
Compares this instance with other, returning true if they are associated with the same Subsets object and if they are at the same point in their enumeration cycle.
bool operator!= (const const_iterator &other)
Compares this instance with other, returning false if they are associated with the same Subsets object and if they are at the same point in their enumeration cycle.
const Coordinates & operator* () const
Dereference operator, when dereferencing this object, you get the set of coordinates this iterator points to.
const_iterator & operator++ ()
Prefix incrementation operator.
const_iterator operator++ (int)
Postfix incrementation operator.
Detailed Description
An iterator class used internaly by the Subsets class.
Given an object of this class, it is possible to cycle through the element it contains with the increment (++) operator.
Member Function Documentation
operator++() [1/2]
const_iterator & LatticeTester::CoordinateSets::Subsets::const_iterator::operator++ ()
Prefix incrementation operator.
Increments this iterator and returns the iterator in its new state.
References const_iterator().
operator++() [2/2]
const_iterator LatticeTester::CoordinateSets::Subsets::const_iterator::operator++ (int)
Postfix incrementation operator.
Increments this iterator and returns a copy of the old object.
References const_iterator(), and LatticeTester::CoordinateSets::Subsets::Subsets().
The documentation for this class was generated from the following file:
latticetester/include/latticetester/CoordinateSets.h