#!/usr/bin/env python
# coding: utf-8

def build(ctx):

    lc_inc_dir = ctx.root.find_dir(ctx.top_dir).find_dir('latcommon/include')
    lb_inc_dir = ctx.root.find_dir(ctx.top_dir).find_dir('latbuilder/include')

    for src in ctx.path.ant_glob('*.cc', excl=['extend']):

        ctx(features='cxx cxxprogram',
                source=src,
                includes=[lb_inc_dir, lc_inc_dir],
                lib=ctx.env.LIB_FFTW + ctx.env.LIB_PROGRAM_OPTIONS,
                stlib=ctx.env.STLIB_FFTW + ctx.env.STLIB_PROGRAM_OPTIONS,
                target=src.name[:-3],
                use=['latbuilder', 'latcommon'],
                install_path=None)

    for src in ctx.path.ant_glob('*.c', excl=['extend']):

        ctx(features='c cprogram',
                source=src,
                includes=[lb_inc_dir, lc_inc_dir],
                lib=ctx.env.LIB_FFTW + ctx.env.LIB_PROGRAM_OPTIONS + ['stdc++', 'm'],
                stlib=ctx.env.STLIB_FFTW + ctx.env.STLIB_PROGRAM_OPTIONS,
                target=src.name[:-2],
                use=['latbuilder', 'latcommon'],
                install_path=None)

    ctx.install_files('${DOCDIR}/examples', ctx.path.ant_glob(['*.cc', '*.c']))

    ctx.recurse('tutorial')

    ctx(features='subst',
            source='myproject/Makefile.in',
            target='myproject/Makefile',
            PREFIX=ctx.env.PREFIX,
            CXXFLAGS =' '.join(ctx.env.CXXFLAGS),
            INCLUDES =' '.join('-I"%s"' % x for x in ctx.env.INCLUDES),
            LIBPATH  =' '.join('-L"%s"' % x for x in ctx.env.LIBPATH),
            LIBRARIES=' '.join('-l"%s"' % x for x in ctx.env.LIB_FFTW + ctx.env.STLIB_FFTW),
            install_path='${DOCDIR}/examples/myproject')

    ctx.install_files('${DOCDIR}/examples/myproject', ctx.path.ant_glob('myproject/*.cc'))
