LatNet Builder Manual: NetBuilder::AbstractDigitalNet Class Reference
NetBuilder::AbstractDigitalNet Class Reference abstract
Abstract class representing digital nets in base 2.
#include <DigitalNet.h>
Inherited by NetBuilder::DigitalNet< NC >.
Public Member Functions
AbstractDigitalNet (Dimension dimension=0, unsigned int nRows=0, unsigned int nCols=0)
Default constructor.
virtual ~AbstractDigitalNet ()=default
Default destructor.
unsigned int numColumns () const
Returns the number of columns of the generating matrices.
unsigned int numRows () const
Returns the number of rows of the generating matrices.
uInteger numPoints () const
Returns the number of points of the net.
uInteger size () const
Returns the number of points of the net.
Dimension dimension () const
Returns the dimension (number of coordinates) of the net.
const GeneratingMatrix & generatingMatrix (Dimension coord) const
Returns the generating matrix corresponding to coordinate coord.
virtual std::string format (OutputStyle outputStyle=OutputStyle::TERMINAL, unsigned int interlacingFactor=1) const =0
Formats the net for output.
virtual bool isSequenceViewable () const =0
Returns a bool indicating whether the net can be viewed as a digital sequence.
Protected Member Functions
AbstractDigitalNet (Dimension dimension, unsigned int nRows, unsigned int nCols, std::vector< std::shared_ptr< GeneratingMatrix > > genMatrices)
Most general constructor.
Protected Attributes
Dimension m_dimension
unsigned int m_nRows
unsigned int m_nCols
std::vector< std::shared_ptr< GeneratingMatrix > > m_generatingMatrices
Detailed Description
Abstract class representing digital nets in base 2.
Digital nets in other bases are not implemented. An abstract digital net essentially corresponds to a vector of generating matrices. This class is used to reason about digital nets whenever we do not need to actually construct them, e.g. to compute figures of merit from the matrices.
Concrete instantiations of this class are done through its derived class called DigitalNet.
Constructor & Destructor Documentation
AbstractDigitalNet() [1/2]
NetBuilder::AbstractDigitalNet::AbstractDigitalNet (Dimension dimension = 0, unsigned int nRows = 0, unsigned int nCols = 0) inline
Default constructor.
Parameters
dimension Number of coordinates in the net.
nRows Number of rows of the generating matrices.
nCols Number of columns of the generating matrices.
References dimension().
Referenced by NetBuilder::DigitalNet< NC >::DigitalNet(), and NetBuilder::DigitalNet< NC >::DigitalNet().
AbstractDigitalNet() [2/2]
NetBuilder::AbstractDigitalNet::AbstractDigitalNet (Dimension dimension, unsigned int nRows, unsigned int nCols, std::vector< std::shared_ptr< GeneratingMatrix > > genMatrices) inline protected
Most general constructor.
Designed to be used by derived classes.
Parameters
dimension Dimension of the net.
nRows Number of rows of the generating matrices.
nCols Number of columns of the generating matrices.
genMatrices Vector of shared pointers to the generating matrices.
References dimension().
Member Function Documentation
format()
virtual std::string NetBuilder::AbstractDigitalNet::format (OutputStyle outputStyle = OutputStyle::TERMINAL, unsigned int interlacingFactor = 1) const pure virtual
Formats the net for output.
Parameters
outputFormat Format of output.
interlacingFactor Interlacing factor of the net.
outputStyle Specific Format of output Machine format.
Implemented in NetBuilder::DigitalNet< NC >.
Referenced by NetBuilder::Task::Eval::outputNet().
generatingMatrix()
const GeneratingMatrix & NetBuilder::AbstractDigitalNet::generatingMatrix (Dimension coord) const inline
Returns the generating matrix corresponding to coordinate coord.
Parameters
coord A coordinate (between 0 and dimension() - 1).
Referenced by NetBuilder::FigureOfMerit::ResolutionGapProjMerit< EmbeddingType::MULTILEVEL >::operator()(), NetBuilder::FigureOfMerit::ResolutionGapProjMerit< EmbeddingType::UNILEVEL >::operator()(), NetBuilder::FigureOfMerit::TValueProjMerit< EmbeddingType::MULTILEVEL, METHOD >::operator()(), and NetBuilder::FigureOfMerit::TValueProjMerit< EmbeddingType::UNILEVEL, METHOD >::operator()().
isSequenceViewable()
virtual bool NetBuilder::AbstractDigitalNet::isSequenceViewable () const pure virtual
Returns a bool indicating whether the net can be viewed as a digital sequence.
Implemented in NetBuilder::DigitalNet< NC >.
The documentation for this class was generated from the following file:
include/netbuilder/DigitalNet.h