LatNet Builder Manual: LatBuilder::MeritSeq::CoordUniformCBC< LR, ET, COMPRESS, PLO, KERNEL, PROD >::Seq< GENSEQ > Class Template Reference
LatBuilder::MeritSeq::CoordUniformCBC< LR, ET, COMPRESS, PLO, KERNEL, PROD >::Seq< GENSEQ > Class Template Reference
Output sequence from the coordinate-uniform CBC algorithm.
#include <CoordUniformCBC.h>
Classes
class const_iterator
Constant iterator.
Public Types
typedef GENSEQ GenSeq
typedef CoordUniformInnerProd::template Seq< GenSeq > ProdSeq
typedef LatBuilder::LatSeq::CBC< LR, ET, GenSeq > LatSeq
typedef LatSeq::size_type size_type
Public Member Functions
Seq (const CoordUniformCBC &parent, const GenSeq &genSeq)
Constructor.
const CoordUniformCBC & cbc () const
Returns a reference to the parent CoordUniformCBC instance.
const LatSeq & latSeq () const
Returns a reference to the internal lattice sequence.
const ProdSeq & prodSeq () const
Returns a reference to the internal inner product sequence.
const_iterator begin () const
Returns an iterator pointing to the first element in the sequence.
const_iterator end () const
Returns an iterator pointing past the last element in the sequence.
Detailed Description
template<LatticeType LR, EmbeddingType ET, Compress COMPRESS, PerLevelOrder PLO, class KERNEL, template< LatticeType, EmbeddingType, Compress, PerLevelOrder > class PROD = CoordUniformInnerProd>
template<typename GENSEQ>
class LatBuilder::MeritSeq::CoordUniformCBC< LR, ET, COMPRESS, PLO, KERNEL, PROD >::Seq< GENSEQ >
Output sequence from the coordinate-uniform CBC algorithm.
It is based on a sequence of lattice definitions.
Template Parameters
GENSEQ Type of sequence of generator values.
Constructor & Destructor Documentation
Seq()
template<LatticeType LR, EmbeddingType ET, Compress COMPRESS, PerLevelOrder PLO, class KERNEL, template< LatticeType, EmbeddingType, Compress, PerLevelOrder > class PROD = CoordUniformInnerProd> template<typename GENSEQ> LatBuilder::MeritSeq::CoordUniformCBC< LR, ET, COMPRESS, PLO, KERNEL, PROD >::Seq< GENSEQ >::Seq (const CoordUniformCBC & parent, const GenSeq< GENSEQ > & genSeq) inline
Constructor.
Parameters
parent Reference to the parent. Kept as a reference, no copy made.
genSeq Sequence of generator values.
References LatBuilder::MeritSeq::CoordUniformCBC< LR, ET, COMPRESS, PLO, KERNEL, PROD >::baseLat(), LatBuilder::MeritSeq::CoordUniformCBC< LR, ET, COMPRESS, PLO, KERNEL, PROD >::CoordUniformCBC(), LatBuilder::MeritSeq::CoordUniformCBC< LR, ET, COMPRESS, PLO, KERNEL, PROD >::innerProd(), prodSeq(), and LatBuilder::MeritSeq::CoordUniformCBC< LR, ET, COMPRESS, PLO, KERNEL, PROD >::weightedState().
Referenced by LatBuilder::MeritSeq::CoordUniformCBC< LR, ET, COMPRESS, PLO, KERNEL, PROD >::Seq< GENSEQ >::const_iterator::seq().
The documentation for this class was generated from the following file:
include/latbuilder/MeritSeq/CoordUniformCBC.h