#!/usr/bin/env python
# coding: utf-8

from waflib import Utils, Task, Build

def build(ctx):

    # install files
    data = [x for x in ctx.path.ant_glob('web_ui/**/*')]
    ctx.install_files('${DATADIR}/latbuilder', data, cwd=ctx.path.find_dir('share'), relative_trick=True)
    ctx.install_files('${BINDIR}', ctx.path.find_node('notebooks/Interface.ipynb'), chmod=Utils.O755)
