LatNet Builder Manual: NetBuilder::Task::Eval Class Reference
NetBuilder::Task::Eval Class Reference
Inherits NetBuilder::Task::Task.
Public Member Functions
Eval (std::unique_ptr< AbstractDigitalNet > net, std::unique_ptr< FigureOfMerit::FigureOfMerit > figure, int verbose=0)
Eval (Eval &&)=default
Dimension dimension () const
Returns the dimension.
unsigned int nRows ()
unsigned int nCols ()
const AbstractDigitalNet & net () const
Returns the best net found by the search task.
virtual std::string outputNet (OutputStyle outputStyle, unsigned int interlacingFactor) const
Returns the best net found by the search task.
virtual std::string format () const
Returns information about the task.
Real meritValue () const
Returns the best merit value found by the search task.
virtual Real outputMeritValue () const
Returns the best merit value found by the search task.
const FigureOfMerit::FigureOfMerit & figureOfMerit () const
virtual void execute ()
Executes the search task.
virtual void reset ()
Resets the task.
virtual void reset (std::unique_ptr< AbstractDigitalNet > net)
Public Member Functions inherited from NetBuilder::Task::Task
Member Function Documentation
execute()
virtual void NetBuilder::Task::Eval::execute () inline virtual
Executes the search task.
The best net and merit value are set in the process.
Implements NetBuilder::Task::Task.
format()
virtual std::string NetBuilder::Task::Eval::format () const inline virtual
Returns information about the task.
Implements NetBuilder::Task::Task.
References dimension().
outputMeritValue()
virtual Real NetBuilder::Task::Eval::outputMeritValue () const inline virtual
Returns the best merit value found by the search task.
Implements NetBuilder::Task::Task.
References meritValue().
outputNet()
virtual std::string NetBuilder::Task::Eval::outputNet (OutputStyle outputStyle, unsigned int interlacingFactor) const inline virtual
Returns the best net found by the search task.
Implements NetBuilder::Task::Task.
References NetBuilder::AbstractDigitalNet::format(), and net().
reset()
virtual void NetBuilder::Task::Eval::reset () inline virtual
Resets the task.
Implements NetBuilder::Task::Task.
The documentation for this class was generated from the following file:
include/netbuilder/Task/Eval.h