#!/usr/bin/env python
# coding: utf-8

def build(ctx):
    data_dir = ctx.path

    # data files
    for dat in data_dir.ant_glob('*.csv'):
        ctx.install_files("${PREFIX}/share/latbuilder/data", dat)
