LatNet Builder Manual: LatBuilder::Vectorize Namespace Reference
LatBuilder::Vectorize Namespace Reference
Helpers to vectorize simple operations.
Classes
struct BinaryOperator
Automatic dispatcher for binary operators.
struct BinaryOperator< OP, true, false >
Vector-scalar specialization of BinaryOperator.
struct BinaryOperator< OP, true, true >
Vector-vector specialization of BinaryOperator.
struct BinaryOperatorResult
Guesses the result type of the binary operator OP given arguments of type T1 and T2.
class IsIndexable
Type traits class that checks if T is indexable with [].
Functions
template<typename OP, typename T1, typename T2>
BinaryOperatorResult< OP, T1, T2 >::type apply (const T1 &x, const T2 &y)
Applies the scalar binary operator OP to x and y.
Detailed Description
Helpers to vectorize simple operations.
Function Documentation
apply()
template<typename OP, typename T1, typename T2> BinaryOperatorResult< OP, T1, T2 >::type LatBuilder::Vectorize::apply (const T1 & x, const T2 & y)
Applies the scalar binary operator OP to x and y.
Example definition of OP:
struct Sum {
   typedef double result_type;
   static constexpr result_type apply(const arg_type& x, const arg_type& y)
   { return x + y; }
};
References apply().
Referenced by LatBuilder::Accumulator< OP, VAL, ACCVAL >::accumulate(), and apply().