LatNet Builder Manual: LatBuilder::Task::Extend< LR, ET, COMPRESS, PLO, FIGURE > Class Template Reference
LatBuilder::Task::Extend< LR, ET, COMPRESS, PLO, FIGURE > Class Template Reference
Search task that extends the number of points of a lattice.
#include <Extend.h>
Inherits LatBuilder::Task::Search< LR, ET >.
Public Types
typedef LatBuilder::Storage< LR, ET, COMPRESS, PLO > Storage
typedef CBCSelector< LR, ET, COMPRESS, PLO, FIGURE >::CBC CBC
typedef CBC::FigureOfMerit FigureOfMerit
typedef Storage::SizeParam SizeParam
Public Types inherited from LatBuilder::Task::Search< LR, ET >
typedef boost::signals2::signal< void(const Search &)> OnLatticeSelected
Public Member Functions
Extend (Storage storage, LatDef< LR, ET > baseLat, FigureOfMerit figure)
Extend (Extend &&other)
virtual void execute ()
Executes the search task.
const Storage & storage () const
Returns a pointer to the storage configuration instance.
const FigureOfMerit & figureOfMerit () const
Returns the figure of merit.
const LatDef< LR, ET > & baseLat () const
Returns the base lattice on which to extend.
const MeritSeq::LatSeqOverCBC< CBC > & latSeqOverCBC () const
Returns the internal lattice sequence.
const CBC & cbc () const
Returns the internal CBC instance.
Public Member Functions inherited from LatBuilder::Task::Search< LR, ET >
Search (Dimension dimension)
Search (Search &&other)
Dimension dimension () const
Returns the dimension.
int verbose () const
void setVerbose (int verbose)
const MeritFilterList< LR, ET > & filters () const
Returns the filters of merit transformations.
MeritFilterList< LR, ET > & filters ()
Returns the filters of merit transformations.
const LatDef< LR, ET > & bestLattice () const
Returns the best lattice found by the search task.
Real bestMeritValue () const
Returns the best merit value found by the search task.
const Functor::MinElement< Real > & minElement () const
MinObserver & minObserver ()
Returns the minimum-element observer.
const MinObserver & minObserver () const
void setObserverVerbosity (int verbose) const
void setObserverTotalDim (Dimension totalDim) const
OnLatticeSelected & onLatticeSelected ()
Lattice-selected signal.
const OnLatticeSelected & onLatticeSelected () const
virtual void reset ()
Initializes the best lattice and merit value.
Protected Member Functions
virtual void format (std::ostream &os) const
Protected Member Functions inherited from LatBuilder::Task::Search< LR, ET >
void selectBestLattice (const LatDef< LR, ET > &lattice, Real merit, bool quiet)
Selects a new best lattice and emits an OnLatticeSelected signal, if quiet is set to false.
Detailed Description
template<LatticeType LR, EmbeddingType ET, Compress COMPRESS, PerLevelOrder PLO, class FIGURE>
class LatBuilder::Task::Extend< LR, ET, COMPRESS, PLO, FIGURE >
Search task that extends the number of points of a lattice.
Template Parameters
ET,COMPRESS Type of storage.
FIGURE Type of figure of merit.
Member Function Documentation
execute()
template<LatticeType LR, EmbeddingType ET, Compress COMPRESS, PerLevelOrder PLO, class FIGURE> virtual void LatBuilder::Task::Extend< LR, ET, COMPRESS, PLO, FIGURE >::execute () inline virtual
Executes the search task.
The best lattice and merit value are set in the process.
Implements LatBuilder::Task::Search< LR, ET >.
References baseLat(), LatBuilder::Task::Search< LR, ET >::dimension(), LatBuilder::Task::Search< LR, ET >::filters(), latSeqOverCBC(), LatBuilder::Task::Search< LR, ET >::selectBestLattice(), and storage().
figureOfMerit()
template<LatticeType LR, EmbeddingType ET, Compress COMPRESS, PerLevelOrder PLO, class FIGURE> const FigureOfMerit & LatBuilder::Task::Extend< LR, ET, COMPRESS, PLO, FIGURE >::figureOfMerit () const inline virtual
Returns the figure of merit.
Implements LatBuilder::Task::Search< LR, ET >.
format()
template<LatticeType LR, EmbeddingType ET, Compress COMPRESS, PerLevelOrder PLO, class FIGURE> virtual void LatBuilder::Task::Extend< LR, ET, COMPRESS, PLO, FIGURE >::format (std::ostream & os) const inline protected virtual
Reimplemented from LatBuilder::Task::Search< LR, ET >.
The documentation for this class was generated from the following file:
include/latbuilder/Task/Extend.h