#!/usr/bin/env python
# coding: utf-8

def build(ctx):
    if ctx.cmd == 'build':
        if not ctx.env.BUILD_CONDA:
            print('not building conda package; Conda (https://www.anaconda.com/download/) is missing')
            return
        top = ctx.srcnode.abspath()
        print(top)
        cmd1 = "Building the conda package, this could take a few minutes..."
        cmd2 = 'export WITHOUT_WAF=' + str(int(not ctx.env.EMBED_LATNET_CONDA)) + \
        ' && %s build python-wrapper/conda_recipe' % (ctx.env.get_flat('CONDA'))
        ctx(
                rule   = cmd1,
                source = 'wscript',
                cwd = top
        )
        ctx(
                rule   = cmd2,
                source = 'wscript',
                cwd = top
        )

    if ctx.cmd == 'install':
        if not ctx.env.BUILD_CONDA:
            print('not building conda package; Conda (https://www.anaconda.com/download/) is missing')
            return

        cmd1 = 'Installing the conda package... this can take a few minutes'
        cmd2 = 'conda create -y -n latnetbuilder || echo "Tried to create latnetbuilder environment"'
        cmd3 = ". activate latnetbuilder && conda install -y --use-local latnetbuilder appmode"

        ctx(
                rule   = cmd1,
                source = 'wscript'
        )
        ctx(
                rule   = cmd2,
                source = 'wscript'
        )
        ctx(
                rule   = cmd3,
                source = 'wscript',
                shell = False
        )