LatNet Builder Manual: LatBuilder::MeritSeq::CoordUniformInnerProdFast< LR, ET, COMPRESS, PLO > Class Template Reference
LatBuilder::MeritSeq::CoordUniformInnerProdFast< LR, ET, COMPRESS, PLO > Class Template Reference
FFT-based implementation of the inner product for a circulant sequence of vector with a single vector.
#include <CoordUniformInnerProdFast.h>
Classes
class Seq
Sequence of inner product values.
Public Types
typedef Storage< LR, EmbeddingType::MULTILEVEL, COMPRESS, PerLevelOrder::CYCLIC > InternalStorage
typedef CoordUniformStateList< LR, EmbeddingType::MULTILEVEL, COMPRESS, PerLevelOrder::CYCLIC > StateList
typedef Storage< LR, ET, COMPRESS >::MeritValue MeritValue
Public Member Functions
template<class K>
CoordUniformInnerProdFast (Storage< LR, ET, COMPRESS, PLO > storage, const Kernel::Base< K > &kernel)
Constructor.
const Storage< LR, ET, COMPRESS, PLO > & storage () const
Returns the storage configuration instance.
const InternalStorage & internalStorage () const
Returns the internal storage configuration instance.
const RealVector & kernelValues () const
Returns the vector of kernel values.
const std::vector< boost::numeric::ublas::range > & levelRanges () const
Returns the vector of per-level ranges of indices.
const std::vector< FFTComplexVector > & circulantFFT () const
Returns the FFT's of the first column of each circulant submatrix in the horizontal block-circulant matrix.
template<class GENSEQ, class E>
Seq< GENSEQ > prodSeq (const GENSEQ &genSeq, const boost::numeric::ublas::vector_expression< E > &vec) const
Creates a new sequence of inner product values by applying a stride permutation based on genSeq to the vector of kernel values, then by computing the inner product with vec.
Protected Types
typedef fftw< Real >::real_vector FFTRealVector
typedef fftw< Real >::complex_vector FFTComplexVector
Detailed Description
template<LatticeType LR, EmbeddingType ET, Compress COMPRESS, PerLevelOrder PLO>
class LatBuilder::MeritSeq::CoordUniformInnerProdFast< LR, ET, COMPRESS, PLO >
FFT-based implementation of the inner product for a circulant sequence of vector with a single vector.
Implemented for integer powers of prime bases, as proposed in [4] .
Computes the inner product with a second vector for all vectors in the sequence at once.
Constructor & Destructor Documentation
CoordUniformInnerProdFast()
template<LatticeType LR, EmbeddingType ET, Compress COMPRESS, PerLevelOrder PLO> template<class K> LatBuilder::MeritSeq::CoordUniformInnerProdFast< LR, ET, COMPRESS, PLO >::CoordUniformInnerProdFast (Storage< LR, ET, COMPRESS, PLO > storage, const Kernel::Base< K > & kernel) inline
Constructor.
Parameters
storage Storage configuration.
kernel Kernel. Used to create a sequence of permuatations of the kernel values evaluated at every one-dimensional lattice point.
References internalStorage(), and storage().
Referenced by LatBuilder::MeritSeq::CoordUniformInnerProdFast< LR, ET, COMPRESS, PLO >::Seq< GENSEQ >::innerProd(), and LatBuilder::MeritSeq::CoordUniformInnerProdFast< LR, ET, COMPRESS, PLO >::Seq< GENSEQ >::Seq().
Member Function Documentation
prodSeq()
template<LatticeType LR, EmbeddingType ET, Compress COMPRESS, PerLevelOrder PLO> template<class GENSEQ, class E> Seq< GENSEQ > LatBuilder::MeritSeq::CoordUniformInnerProdFast< LR, ET, COMPRESS, PLO >::prodSeq (const GENSEQ & genSeq, const boost::numeric::ublas::vector_expression< E > & vec) const inline
Creates a new sequence of inner product values by applying a stride permutation based on genSeq to the vector of kernel values, then by computing the inner product with vec.
Parameters
genSeq Sequence of generator values.
vec Second operand in the inner product.
The documentation for this class was generated from the following file:
include/latbuilder/MeritSeq/CoordUniformInnerProdFast.h