LatNet Builder Manual: NTL::matrix< T > Class Template Reference
NTL::matrix< T > Class Template Reference
A subclass of the NTL::Mat<T> class.
#include <ntlwrap.h>
Inherits Mat< T >.
Public Types
typedef std::int64_t size_type
Public Member Functions
matrix ()
Empty constructor.
matrix (const Mat< T > &a)
Copy constructor.
matrix (size_type size1, size_type size2)
Allocation constructor.
void resize (size_type size1, size_type size2)
Set the matrix dimensions to size1 \(\times\)size2.
void clear ()
Releases space and sets the matrix this size \(0\times 0\).
size_type size1 () const
Returns the number of rows of the matrix.
size_type size2 () const
Returns the number of columns of the matrix.
T & operator() (size_type i, size_type j)
Overload to change the indexation reference for (i,j) operator to start from 0.
const T & operator() (size_type i, size_type j) const
Detailed Description
template<typename T>
class NTL::matrix< T >
A subclass of the NTL::Mat<T> class.
It extends its parent with a few methods and overloads a few others with more compatible defaults.
Constructor & Destructor Documentation
matrix() [1/2]
template<typename T > NTL::matrix< T >::matrix (const Mat< T > & a) inline
Copy constructor.
Creates a new matrix that is a copy of a.
Parameters
a Matrix to be copied.
matrix() [2/2]
template<typename T > NTL::matrix< T >::matrix (size_type size1, size_type size2) inline
Allocation constructor.
Creates and allocates a size1 \(\times\)size2 matrix, initializing the elements T with their default constructor.
Parameters
size1 Height of the matrix
size2 Width of the matrix
Member Function Documentation
clear()
template<typename T > void NTL::matrix< T >::clear () inline
Releases space and sets the matrix this size \(0\times 0\).
This uses NTL::Mat<T>::kill().
operator()()
template<typename T > T & NTL::matrix< T >::operator() (size_type i, size_type j) inline
Overload to change the indexation reference for (i,j) operator to start from 0.
In NTL::Vec<T> the (i,j) operator starts from 1 which is not compatible with boost.
resize()
template<typename T > void NTL::matrix< T >::resize (size_type size1, size_type size2) inline
Set the matrix dimensions to size1 \(\times\)size2.
This uses NTL::Mat<T>::SetDims(size1, size2).
Parameters
size1 New height of the matrix.
size2 New width of the matrix.
References NTL::matrix< T >::size1(), and NTL::matrix< T >::size2().
Referenced by LatticeTester::IntLattice< Int, BasInt, Dbl, RedDbl >::IntLattice(), and LatticeTester::IntLatticeBasis< Int, BasInt, Dbl, RedDbl >::IntLatticeBasis().
The documentation for this class was generated from the following file:
latticetester/include/latticetester/ntlwrap.h