LatNet Builder Manual: NetBuilder::FigureOfMerit::CoordUniformFigureOfMerit< KERNEL, ET > Class Template Reference
NetBuilder::FigureOfMerit::CoordUniformFigureOfMerit< KERNEL, ET > Class Template Reference
Class which represents a coordinate uniform figure of merit based on a kernel which is the template parameter.
#include <CoordUniformFigureOfMerit.h>
Inherits NetBuilder::FigureOfMerit::CBCFigureOfMerit.
Public Types
typedef std::unique_ptr< LevelCombiner::LevelCombiner > pCombiner
Public Member Functions
CoordUniformFigureOfMerit (std::unique_ptr< LatticeTester::Weights > weights, KERNEL kernel=KERNEL(), pCombiner combiner=std::make_unique< LevelCombiner::LevelCombiner >())
Constructor.
const LatticeTester::Weights & weights () const
Returns the projection-dependent weights \(\gamma_{\mathfrak u}\).
const KERNEL & kernel () const
Returns the coordinate-uniform kernel.
bool symmetric () const
Returns a bool indicating whether the kernel is symmetric.
virtual std::string format () const override
Output information about the figure of merit.
virtual std::unique_ptr< CBCFigureOfMeritEvaluator > evaluator () override
Returns a std::unique_ptr to an evaluator for the figure of merit.
virtual Accumulator accumulator (Real initialValue) const override
Creates a new accumulator.
Public Member Functions inherited from NetBuilder::FigureOfMerit::CBCFigureOfMerit
virtual ~CBCFigureOfMerit ()=default
Virtual default destructor.
Public Member Functions inherited from NetBuilder::FigureOfMerit::FigureOfMerit
virtual ~FigureOfMerit ()=default
Virtual default destructor.
std::unique_ptr< FigureOfMeritEvaluator > evaluator ()
Returns a std::unique_ptr to an evaluator for the figure of merit.
Static Public Member Functions
static constexpr LatBuilder::Compress suggestedCompression ()
Returns the suggested compression for this kernel.
Detailed Description
template<class KERNEL, LatBuilder::EmbeddingType ET>
class NetBuilder::FigureOfMerit::CoordUniformFigureOfMerit< KERNEL, ET >
Class which represents a coordinate uniform figure of merit based on a kernel which is the template parameter.
Constructor & Destructor Documentation
CoordUniformFigureOfMerit()
template<class KERNEL, LatBuilder::EmbeddingType ET> NetBuilder::FigureOfMerit::CoordUniformFigureOfMerit< KERNEL, ET >::CoordUniformFigureOfMerit (std::unique_ptr< LatticeTester::Weights > weights, KERNEL kernel = KERNEL(), pCombiner combiner = std::make_unique<LevelCombiner::LevelCombiner>()) inline
Constructor.
Parameters
weights See LatBuilder::WeightedFigureOfMerit::WeightedFigureOfMerit for details about this parameter.
kernel Kernel (\(\omega\) in the reference paper). See the LatBuilder::Kernel namespace for examples.
combiner Combiner used to combine multilevel merits into a single value merit. Not used is ET is UNILEVEL.
References kernel(), and weights().
Member Function Documentation
accumulator()
template<class KERNEL, LatBuilder::EmbeddingType ET> virtual Accumulator NetBuilder::FigureOfMerit::CoordUniformFigureOfMerit< KERNEL, ET >::accumulator (Real initialValue) const inline override virtual
Creates a new accumulator.
Parameters
initialValue Initial accumulator value.
Implements NetBuilder::FigureOfMerit::CBCFigureOfMerit.
evaluator()
template<class KERNEL, LatBuilder::EmbeddingType ET> virtual std::unique_ptr< CBCFigureOfMeritEvaluator > NetBuilder::FigureOfMerit::CoordUniformFigureOfMerit< KERNEL, ET >::evaluator () inline override virtual
Returns a std::unique_ptr to an evaluator for the figure of merit.
Implements NetBuilder::FigureOfMerit::CBCFigureOfMerit.
format()
template<class KERNEL, LatBuilder::EmbeddingType ET> virtual std::string NetBuilder::FigureOfMerit::CoordUniformFigureOfMerit< KERNEL, ET >::format () const inline override virtual
Output information about the figure of merit.
Implements NetBuilder::FigureOfMerit::FigureOfMerit.
References LatticeTester::Weights::format(), kernel(), and weights().
weights()
template<class KERNEL, LatBuilder::EmbeddingType ET> const LatticeTester::Weights & NetBuilder::FigureOfMerit::CoordUniformFigureOfMerit< KERNEL, ET >::weights () const inline
Returns the projection-dependent weights \(\gamma_{\mathfrak u}\).
Referenced by CoordUniformFigureOfMerit(), and format().
The documentation for this class was generated from the following file:
include/netbuilder/FigureOfMerit/CoordUniformFigureOfMerit.h